/* AUTO-GENERATED by build_today_focus.py from today_focus.json — do not edit by hand.
   Generated for asOf 2026-06-26. Re-run: python build_today_focus.py */
window.TODAY_FOCUS = {
  "asOf": "2026-06-26",
  "generated": "2026-06-26",
  "sweep": {
    "sources": [
      "Reuters",
      "WSJ",
      "Bloomberg",
      "Yahoo Finance",
      "Seeking Alpha",
      "Barron's"
    ],
    "rule": "A fact is stated only if >=2 independent sources agree. Pending/forward events are kept in the future tense. Every datapoint is tagged sourced or estimated.",
    "note": "Refreshed on the 26-Jun-2026 (Friday) sweep. The dollar melt-up / hawkish-hold regime is intact and has HARDENED: May PCE (released 25-Jun) re-accelerated to 4.1% headline (from 3.8%) with core 3.4% — the hottest core since Oct-2023 and above the 3.3% consensus — on the energy shock, and the Fed's path repriced more hawkish still (BofA now sees three 2026 hikes to 4.25-4.50%; market-implied odds of a September hike jumped to ~68% from ~29% a week ago; 17 of 18 officials see inflation risk to the upside). DXY pushed to ~101.7 mid-week (its highest since March-2025) before easing to ~101.4 Thursday on SUSPECTED MoF intervention; EUR/USD is pinned ~1.143 and cable ~1.35 (BoE on hold 3.75%). The yen is the pressure point: USD/JPY ran to ~161.5-162 — 40-year highs, the weakest yen since 1986 — with new FinMin Katayama and US Treasury's Bessent agreeing to 'act if necessary' and a suspected intervention Thursday; the BoJ's June Summary of Opinions still favours more hikes, yet the wide differential keeps the carry dominant. The 10Y backed up to ~4.45-4.50%. The week's earnings landed: FedEx FQ4 (Tue 23-Jun) BEAT but sold off ~6% on cautious transition-year guidance after the Freight spin-off; Micron FQ3 (Wed 24-Jun) delivered a record blow-out (rev $41.5B, EPS $25.11, a $50B Q4 guide) and jumped ~13-15% to ~$1,200. Nike FQ4 is still ahead (Tue 30-Jun). Brent eased below $75 (from ~$79) as Hormuz flows ran at their fastest since the war, though a tanker struck off Oman revived the re-escalation tail; gold slid to ~$4,010 (~28% below the Jan record) on the strong dollar. Implied moves are options-desk estimates (labelled estimated); consensus figures are flagged where not dual-confirmed."
  },
  "earnings": [
    {
      "id": "mu-fq3-react",
      "stance": "post-print",
      "tradeStatement": "Stay long Micron (MU) but express it with discipline after the record FQ3 — rev $41.5B and a $50B Q4 guide drove the stock up ~13-15% to ~$1,200, so the HBM/AI-memory thesis is now confirmed AND priced; for concentrated holders monetise the gap with a zero-cost collar or call-overwrite rather than chasing, and add only on pullbacks.",
      "intent": "add",
      "action": "Ride / monetise the gap",
      "preferredExpression": "Zero-cost collar",
      "name": "Micron Technology",
      "ticker": "MU",
      "sector": "Technology",
      "assetClass": "Equity",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "high",
        "structured": false
      },
      "naturalExpression": "Direct equity",
      "headline": "Micron printed a record blow-out and jumped ~14% to ~$1,200 — the thesis is confirmed and now priced.",
      "thesis": "Micron reported FQ3 after the close on 24 June and it was the print of the quarter: record revenue $41.46B (beating consensus by ~$5.64B), non-GAAP EPS $25.11 (vs ~$20.71), and a Q4 guide of $49-51B (~$50B midpoint, ~$6.55B above the Street) with EPS $30-32. HBM3E/HBM4 are sold out through calendar 2027 and demand extends into 2028; HBM4 12-high is ramping ~2x faster than HBM3E with over $1B already shipped. The stock gapped ~13-15% to ~$1,200 (Goldman lifted its target to $1,100). The 2027 pricing thesis is now confirmed — but also largely in the price after the gap. This is no longer a 'buy the event' setup; it is a 'how do I hold a name at an all-time high after a 14% pop' problem. For concentrated holders, monetise the move with a collar or overwrite; for others, add on pullbacks, not into the gap.",
      "themeId": "ai",
      "offThemeWhy": null,
      "structures": [
        "Zero-cost collar",
        "Call overwrite",
        "Phoenix autocall",
        "Direct equity",
        "Buffered note"
      ],
      "variant": {
        "street": "Analysts raised targets across the board on the record print and $50B guide (Goldman to $1,100)",
        "us": "Thesis confirmed but largely priced after a ~14% gap to ATHs — hold via a collar/overwrite, add only on dips",
        "gap": "The crowd chases the gap; the edge now is in the expression (monetise the move) rather than the direction"
      },
      "changeMyMind": "Guidance or channel checks pointing to 2027 HBM pricing rolling over, or the booked-capacity contracts being renegotiated — the 2027 pricing path, not the quarter just reported, is the thesis.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "A ~14% gap to all-time highs on a blow-out leaves little clean edge chasing — the reaction is broadly proportionate to the print.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "Unanimously bullish sell-side; Goldman raised its target to $1,100 from $900 and the cohort lifted estimates on the $50B guide.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated, just-landed blow-out (24 Jun) — record revenue and a guide-up that re-rated the name.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Crowded long at all-time highs after the gap — momentum, not a washed-out or short-squeeze setup.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 6,
        "maxRaw": 8,
        "score": 75,
        "tier": "High",
        "label": "High — data gap",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-24",
        "reportWhen": "after close",
        "result": "Blow-out beat — record revenue $41.46B (beat by ~$5.64B), non-GAAP EPS $25.11 (vs ~$20.71); Q4 guided $49-51B (~$50B mid, ~$6.55B above consensus) with EPS $30-32; HBM sold out through CY2027 into 2028",
        "resultSource": "sourced",
        "reaction": "Shares jumped ~13-15% after the print to ~$1,200; Goldman raised its price target to $1,100 from $900",
        "reactionSource": "sourced",
        "watch": "2027 HBM pricing durability, the HBM4 ramp, and whether the post-gap momentum holds at all-time highs."
      },
      "facts": [
        {
          "text": "Micron reported FQ3 FY26 on 24 Jun: record revenue $41.46B (beat consensus by ~$5.64B), non-GAAP EPS $25.11 (vs ~$20.71)",
          "tag": "sourced"
        },
        {
          "text": "Q4 guided to $49-51B (~$50B midpoint, ~$6.55B above the Street) with non-GAAP EPS $30-32; HBM3E/HBM4 booked through CY2027, demand into 2028",
          "tag": "sourced"
        },
        {
          "text": "Shares jumped ~13-15% after the print to ~$1,200; Goldman Sachs lifted its target to $1,100 from $900",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Investing.com (earnings-call transcript)",
          "kind": "analysis"
        },
        {
          "name": "TradingKey",
          "kind": "analysis"
        },
        {
          "name": "TheStreet / Yahoo Finance",
          "kind": "news"
        }
      ],
      "kind": "earnings"
    },
    {
      "id": "fdx-fq4-react",
      "stance": "post-print",
      "tradeStatement": "Don't reflexively buy the FedEx (FDX) dip — FQ4 beat ($6.31 EPS on $25.0B) but the stock fell ~6% because the first post-Freight-spin-off guide for CY2026 ($16.90-18.10) reads as a cautious transition year; the global-trade bellwether is flashing caution, so play the reaction with defined risk (buffered note or wait), not a naked add.",
      "intent": "add",
      "action": "Wait / defined-risk entry",
      "preferredExpression": "Buffered note",
      "name": "FedEx",
      "ticker": "FDX",
      "sector": "Industrials",
      "assetClass": "Equity",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "high",
        "structured": false
      },
      "naturalExpression": "Direct equity",
      "headline": "FedEx beat but fell ~6% on a cautious first post-spin-off guide — the trade bellwether is flashing yellow.",
      "thesis": "FedEx reported FQ4 after the close on 23 June: adjusted EPS $6.31 on revenue $25.0B, beating ~$5.92 and ~$24.0B, and it completed the FedEx Freight spin-off. Yet the stock fell ~3.6% in the session and ~6% after hours — the first standalone CY2026 guide ($16.90-18.10 adjusted EPS, ~11% consolidated revenue growth) reads as a cautious, cost-pressured transition year. Unlike a clean capex-overshoot dip, this selloff reflects genuinely soft forward guidance from the global-trade / industrial bellwether — a yellow flag for the 'broadening beyond mega-caps' cyclical rotation, not just the single stock. Play the reaction with discipline: a defined-risk re-entry (buffered note) or wait for the dust to settle, rather than chasing the bounce.",
      "themeId": "broaden",
      "offThemeWhy": null,
      "structures": [
        "Buffered note",
        "Direct equity",
        "Call overwrite",
        "Quality basket"
      ],
      "variant": {
        "street": "Bulls point to the beat, the cheap multiple and the spin-off unlocking value",
        "us": "The cautious transition-year guide from the trade bellwether is the signal — wait, don't chase the dip",
        "gap": "Market may under-weight how a soft freight/industrial guide reads through to the broadening-rotation thesis"
      },
      "changeMyMind": "A re-acceleration in freight demand or DRIVE/Network 2.0 cost savings clearly beating the cautious guide — evidence the transition year is better than feared turns the wait into an add.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "A beat that sold off ~6% offers a dip, but the cautious forward guide is legitimate — not a clean misprice.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Cheap multiple but ratings mixed; the soft transition-year guide splits the Street.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated, just-landed reaction (23 Jun) — a beat overshadowed by cautious guidance and spin-off transition noise.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Cyclical and sentiment-sensitive, but not at a positioning extreme after the drop.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 5,
        "maxRaw": 8,
        "score": 62,
        "tier": "Medium",
        "label": "Medium",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-23",
        "reportWhen": "after close",
        "result": "Beat — adjusted EPS $6.31 on revenue $25.0B (vs ~$5.92 / ~$24.0B); completed the FedEx Freight spin-off; CY2026 guided to $16.90-18.10 adjusted EPS on ~11% consolidated revenue growth",
        "resultSource": "sourced",
        "reaction": "Shares fell ~3.6% in the session (to ~$316.83) and ~6% after hours (to ~$297.70) on the cautious transition-year guide and spin-off cost pressures",
        "reactionSource": "sourced",
        "watch": "Freight-demand trajectory, Network 2.0 / DRIVE cost savings, tariff drag and whether the cautious CY2026 guide proves conservative."
      },
      "facts": [
        {
          "text": "FedEx reported FQ4 FY26 on 23 Jun: adjusted EPS $6.31 on revenue $25.0B, beating ~$5.92 / ~$24.0B; it completed the FedEx Freight spin-off",
          "tag": "sourced"
        },
        {
          "text": "CY2026 guided to $16.90-18.10 adjusted EPS on ~11% consolidated revenue growth — a cautious first standalone guide",
          "tag": "sourced"
        },
        {
          "text": "Shares fell ~3.6% to ~$316.83 in the session and ~6% after hours to ~$297.70 on the transition-year guide",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "GuruFocus",
          "kind": "analysis"
        },
        {
          "name": "Investing.com",
          "kind": "news"
        },
        {
          "name": "AlphaStreet",
          "kind": "calendar"
        }
      ],
      "kind": "earnings"
    },
    {
      "id": "nke-fq4",
      "stance": "pre-position",
      "tradeStatement": "Long Nike (NKE) into FQ4 on 30 June — a single-name turnaround bet (the 'Win Now' reset, China inventory clear-down, tariff-refund one-off) priced for bad news; express it with a structure (reverse convertible / cash-secured puts) given a low bar, not naked stock.",
      "intent": "add",
      "action": "Pre-position with a structure",
      "preferredExpression": "Cash-secured puts",
      "name": "Nike",
      "ticker": "NKE",
      "sector": "Consumer",
      "assetClass": "Equity",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "high",
        "structured": false
      },
      "naturalExpression": "Direct equity",
      "headline": "Nike FQ4 on 30 June — a low-bar turnaround print into a 'better-than-feared' setup",
      "thesis": "Nike reports fiscal Q4 after the close on Tuesday 30 June, with consensus around $0.12 EPS on ~$10.85B revenue — a deliberately low bar. This is a company-specific turnaround: CEO Elliott Hill's 'Win Now' reset is showing early stabilisation but not yet the revenue or margin inflection that justifies multiple expansion, and management is steering a self-imposed ~20% China revenue decline in Q4 to clear inventory. A one-off tariff-refund gain may flatter the headline. Off the desk's strategic themes, but a real dated catalyst for any book with consumer-discretionary exposure — and a classic 'better-than-feared' setup best expressed with a defined-risk structure given how low expectations sit.",
      "themeId": null,
      "offThemeWhy": "No standing desk theme on consumer discretionary — this is a single-name turnaround catalyst, judged on its own merit, not a strategic house view.",
      "structures": [
        "Direct equity",
        "Reverse convertible",
        "Cash-secured puts",
        "Buffered note"
      ],
      "changeMyMind": "China decline failing to stabilise or gross margins falling further ex-tariff-refund — the turnaround thesis depends on China bottoming and margin inflecting, not a one-off refund.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Implied ~8% vs ~7% realised — modestly rich for a turnaround print, but the low bar caps the asymmetry.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Street cautious — lower YoY EPS expected and the turnaround running slow; no clean buy-side alignment.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated FQ4 after the close on 30 Jun — a real, scheduled single-name catalyst.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Beaten-down name with a low bar and some short interest, but the slow turnaround keeps it from a clean squeeze.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 5,
        "maxRaw": 8,
        "score": 62,
        "tier": "Medium",
        "label": "Medium",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-30",
        "reportWhen": "after close",
        "impliedMovePct": 8.0,
        "impliedSource": "estimated",
        "historicalAvgMovePct": 7.0,
        "historicalSource": "estimated",
        "impliedVsHist": "rich",
        "watch": "China revenue trajectory (managed ~-20%), gross-margin recovery ex the tariff-refund one-off, and the FY27 guide."
      },
      "facts": [
        {
          "text": "Nike reports FQ4 fiscal-2026 results after the close on 30 June; consensus ~$0.12 EPS on ~$10.85B revenue",
          "tag": "sourced"
        },
        {
          "text": "Management is steering a self-imposed ~20% China revenue decline in Q4 to clear inventory; a one-off tariff-refund gain is expected to flatter the headline",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Intellectia / GuruFocus",
          "kind": "calendar"
        },
        {
          "name": "Seeking Alpha",
          "kind": "analysis"
        },
        {
          "name": "Benzinga",
          "kind": "analysis"
        }
      ],
      "kind": "earnings"
    }
  ],
  "exEarnings": [
    {
      "id": "gold-pullback",
      "tradeStatement": "Long gold (XAU) — accumulate the deeper pullback to ~$4,010 as strategic ballast; a bet on continued central-bank buying and currency debasement, sized to the protection gap, not a tactical momentum trade.",
      "intent": "protect",
      "tickers": [
        "XAU",
        "GLD",
        "4GLD",
        "GDX",
        "IAU",
        "GLDM"
      ],
      "name": "Gold — accumulate the pullback",
      "ticker": "XAU",
      "sector": "Gold",
      "assetClass": "Commodity",
      "bucket": "Preservation",
      "goalType": "protection",
      "riskProfile": {
        "vol": "moderate",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Physical / ETC",
      "headline": "Gold ~$4,010 on the strong-dollar slide while central banks keep buying",
      "thesis": "Gold has slid to around $4,010 — roughly 28% below its January record — as the hawkish Fed, a 4.1% PCE print and a DXY above 101 keep pressuring it near-term. The strategic case is unchanged: central banks stay net buyers and every major bank's year-end target sits well above spot. For under-protected books the dollar-driven dip is a deeper, better accumulation window in the cleanest debasement hedge — sized to the protection gap, not chased.",
      "themeId": "gold",
      "offThemeWhy": null,
      "structures": [
        "Physical / ETC",
        "Gold accumulator",
        "Capital-protected note"
      ],
      "variant": {
        "street": "Every major bank bullish — year-end targets well above spot; central banks net buyers",
        "us": "Same direction — accumulate the deeper pullback into under-protected books",
        "gap": null
      },
      "changeMyMind": "Central banks turning net sellers for two consecutive quarters, or real yields breaking decisively higher.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "estimated",
            "note": "Bank targets ~30-50% above spot versus gold's normal trailing move — roughly a 1.5-2x asymmetry to the upside, wider after the slide to ~$4,010.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "No single dated catalyst — a structural accumulation on a price pullback.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "Every major bank's year-end target sits above spot and central banks are net buyers — sell-side and flow both confirm.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Driver specificity yes (sourced central-bank tonnage and named bank targets), but no variant edge — this is the consensus call, not a differentiated one.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core to the Gold & Currency house view as strategic ballast.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "~28% off the highs with positioning reset — neither washed-out nor crowded; mild fuel.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Below the January high and sliding near-term, but the long-term uptrend (above the rising 200-day) is intact — confirms on balance.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 10,
        "maxRaw": 15,
        "score": 67,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "Spot ~$4,010 (26 Jun)",
        "detail": "~28% below the 28-Jan record of $5,589; a continued strong-dollar slide as DXY pushed above 101 and PCE re-accelerated to 4.1%; central banks net +244t in Q1 and +17t in April; China adding for 18 straight months.",
        "source": "sourced",
        "watch": "The strong dollar / hawkish Fed path as the near-term headwind; central-bank demand as the marginal buyer underpinning the dip."
      },
      "facts": [
        {
          "text": "Gold ~$4,010 on 26 Jun, about 28% below the 28-Jan all-time high of $5,589, on a continued strong-dollar / hawkish-Fed slide",
          "tag": "sourced"
        },
        {
          "text": "Central banks net buyers: +244t in Q1 2026, +17t in April; China 18 consecutive months",
          "tag": "sourced"
        },
        {
          "text": "Bank year-end targets: Goldman $5,400, JPMorgan ~$6,000, Morgan Stanley $5,200, UBS $5,500",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "World Gold Council",
          "kind": "data"
        },
        {
          "name": "JPMorgan Research",
          "kind": "analysis"
        },
        {
          "name": "Trading Economics / Fortune",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "ai-power",
      "tradeStatement": "Long the power & grid build-out (utilities, gas, nuclear) — a lower-beta way to be long the AI theme that pays contracted income; a bet on structural datacenter electricity demand, not on interest rates.",
      "intent": "income",
      "name": "AI power & the grid",
      "ticker": "",
      "sector": "Utilities",
      "assetClass": "Equity",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "low",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Utility basket",
      "headline": "Electricity is the binding constraint on AI",
      "thesis": "Datacenter electricity demand is on track for roughly 1,050 TWh in 2026 — doubling in a few years — with gas and nuclear the dispatchable supply. Owning the power and grid build-out is the lower-beta way to stay long the AI theme, and it pays contracted income while it compounds. Micron's record HBM print this week is another reminder that the AI build-out — and its power bill — keeps scaling.",
      "themeId": "power",
      "offThemeWhy": null,
      "structures": [
        "Utility basket",
        "Thematic basket",
        "HALO basket (ACM+)"
      ],
      "variant": {
        "street": "Crowds the AI chip names to own the theme",
        "us": "Own the power and grid bottleneck instead — lower-beta, contracted income, still under-owned",
        "gap": "The market pays up for compute and underprices the electricity constraint behind it"
      },
      "changeMyMind": "Datacenter load-growth forecasts being cut, or utility rate-base and PPA approvals stalling.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "estimated",
            "note": "Datacenter power demand roughly doubling — a large structural move versus the sector's normal drift.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "A structural demand story rather than a single dated event.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "IEA data and some sell-side support, but no independent breakout / flow confirmation yet.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 2,
            "dq": "estimated",
            "note": "Quantified driver (IEA: datacenter load ~1,050 TWh, roughly doubling) and a real variant — own the power bottleneck rather than the crowded chips. Driver yes, variant yes.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core Power & Infrastructure house view.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 2,
            "dq": "estimated",
            "note": "Still under-owned versus the chip names — the crowd is clearly not yet with us, which is fuel.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Multi-year rate-base and load growth; the trend is constructive but there's no clean breakout off the moving averages yet — mixed.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 11,
        "maxRaw": 15,
        "score": 73,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "~1,050 TWh datacenter demand by 2026",
        "detail": "IEA projects datacenter electricity use approaching ~1,050 TWh by 2026; dispatchable gas and nuclear lead the supply, with SMRs entering after 2030.",
        "source": "sourced",
        "watch": "Utility rate-base approvals, datacenter PPAs and nuclear/SMR newsflow."
      },
      "facts": [
        {
          "text": "IEA: datacenter electricity use approaching ~1,050 TWh by 2026, more than double recent levels",
          "tag": "sourced"
        },
        {
          "text": "Gas and nuclear are the dispatchable supply; SMRs enter the mix after 2030",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "IEA — Energy & AI",
          "kind": "data"
        },
        {
          "name": "Morgan Stanley",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "lock-yields",
      "tradeStatement": "Long high-quality duration — extend from cash / bills into 5-10y govt / IG to lock ~4.4-4.5% yields; a bet that carry plus eventual cuts beats cash, accepting mark-to-market risk while the Fed stays hawkish.",
      "intent": "income",
      "name": "Quality carry — get paid to wait",
      "ticker": "",
      "sector": "Rates",
      "assetClass": "Fixed Income",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "low",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Govt / IG bonds",
      "headline": "PCE ran hot and the Fed turned more hawkish — own the carry, not the convexity",
      "thesis": "May PCE (released 25 June) re-accelerated to 4.1% headline with core 3.4% — the hottest core since Oct-2023 — and the Fed's path repriced more hawkish: BofA now sees three 2026 hikes to 4.25-4.50% and market-implied September-hike odds jumped to ~68%. The 'extend before the cuts' convexity trade is gone for now; the case left is simpler and still good — you are paid ~4.5% in high-quality intermediate bonds to wait, ballast that cash can't give a book with equities near all-time highs. Add duration for income and diversification, not for a near-term rally.",
      "themeId": "duration",
      "offThemeWhy": null,
      "structures": [
        "Bond ladder",
        "Govt / IG bonds",
        "Extend duration"
      ],
      "variant": {
        "street": "The hot PCE backs up yields; the Street is split between a 2026 hike and a 2027 pivot",
        "us": "Own quality carry now — ~4.5% is paid ballast; don't bank on near-term cuts (or fear every hike)",
        "gap": "The market may still be too optimistic on the timing of the first cut"
      },
      "changeMyMind": "Inflation rolling back toward target (pulling the first cut forward), or the Fed actually hiking through 4.5% — either end of the barbell breaks the simple carry case.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Earning ~4.5% with cuts now a 2027 story — a carry trade with limited near-term convexity, a modest expected move versus normal bond ranges.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "The 25-Jun PCE has landed hot; the next dated catalyst (14 Jul CPI, 29-30 Jul FOMC) is weeks out — structural, not imminent.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "sourced",
            "note": "The hot PCE is sourced fact, but the Street is split on the path — alignment is weaker than a clean carry consensus.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "sourced",
            "note": "Quantified, sourced drivers (PCE 4.1% / core 3.4%, hawkish repricing, 10Y ~4.5%), but mostly the consensus read — a modest variant on cut timing.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core Fixed Income house view — quality income and ballast, even with the cut delayed.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "sourced",
            "note": "The crowd is still parked in cash and bills; extending is the contrarian-leaning move.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "10Y at ~4.45-4.50% on the hawkish repricing; the price trend is mixed — neutral-to-confirming for a carry buyer.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 8,
        "maxRaw": 15,
        "score": 53,
        "tier": "Watch",
        "label": "Watchlist",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "PCE 4.1% / core 3.4%; hawkish repricing; 10Y ~4.45-4.50%",
        "detail": "May PCE (25 Jun) re-accelerated to 4.1% headline, core 3.4% (hottest core since Oct-2023, above the 3.3% consensus). BofA now sees three 2026 hikes to 4.25-4.50%; September-hike odds ~68% (from ~29% a week ago). 10Y backed up to ~4.45-4.50%.",
        "source": "sourced",
        "watch": "The 14 Jul CPI and the 29-30 Jul FOMC — whether the energy-led inflation hardens the hawkish path."
      },
      "facts": [
        {
          "text": "May PCE re-accelerated to 4.1% y/y headline with core 3.4% (released 25 Jun) — the hottest core since Oct-2023 and above the 3.3% consensus",
          "tag": "sourced"
        },
        {
          "text": "BofA now forecasts three 2026 Fed hikes to 4.25-4.50%; market-implied September-hike odds jumped to ~68% from ~29% a week earlier",
          "tag": "sourced"
        },
        {
          "text": "The 10Y Treasury yield sits ~4.45-4.50% after the hawkish repricing",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "CBS / NBC (PCE)",
          "kind": "news"
        },
        {
          "name": "Fortune / CNBC (Fed path)",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "rate-range-accrual",
      "tradeStatement": "Buy a ~12-month 10-year Treasury range accrual note — earn an enhanced ~7.5% p.a. coupon (vs ~4.0% on cash) for each day the 10Y yield fixes inside a 4.00-4.90% band; with the 10Y at ~4.45-4.50% you are paid to hold the view that a hawkish-hold Fed keeps the long end boxed below the proven 5% ceiling, forgoing the coupon only on a decisive break above 4.90% or below 4.00%.",
      "intent": "income",
      "action": "Generate income",
      "preferredExpression": "Range accrual note",
      "name": "10Y range accrual",
      "ticker": "US 10Y",
      "sector": "Rates",
      "assetClass": "Fixed Income",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "low",
        "beta": "low",
        "structured": true
      },
      "naturalExpression": "Range accrual note",
      "trigger": "The 25-Jun PCE (4.1% headline, core 3.4%) and the more-hawkish Fed repricing (BofA three hikes; ~68% September-hike odds) cap the 10Y from both sides — a hot-inflation floor that stops it rallying under 4%, a policy path anchored against a runaway break through 5% — exactly the boxed-in regime a range accrual is paid to harvest, with the 10Y holding ~4.45-4.50% mid-range as DXY pushed above 101.",
      "headline": "The hot PCE and hawkish repricing box the 10Y below 5% — get paid an enhanced coupon to hold the range",
      "thesis": "May PCE re-accelerated to 4.1% (core 3.4%) on 25 June and the Fed path repriced more hawkish (BofA three hikes to 4.25-4.50%, ~68% September-hike odds) — a stance that boxes in the 10Y from both sides, with the 10Y at ~4.45-4.50% sitting mid-range. The TOP of the band is the harder call and the case is specific: 5% has been a proven ceiling — the 10Y peaked near 5.0% in October 2023 and has failed there on every test since, because at ~5% nominal (~2%+ real) duration is the cheapest in two decades and each approach draws heavy real-money buying — pensions and insurers matching liabilities, foreign reserve managers, and asset allocators rotating out of richly-valued equities. The BOTTOM (~4.00%) is held by sticky inflation — PCE re-accelerating to 4.1% on the energy shock — plus no cuts until 2027 to fuel a rally and an elevated term premium on heavy Treasury supply, all of which keep a floor under long yields. So a 12-month 10Y range accrual pays an enhanced ~7.5% p.a. coupon (vs ~4.0% on cash) for each day the yield fixes inside 4.00-4.90%: you are paid to hold the boxed-in view, with the coupon forgone only on the days it breaks out. Capital is returned at par at maturity (issuer credit aside) — more than cash without an outright duration bet.",
      "themeId": "duration",
      "offThemeWhy": null,
      "structures": [
        "Range accrual note",
        "Reverse convertible",
        "Current-coupon ladder",
        "T-bill / muni ladder"
      ],
      "variant": {
        "street": "Bears see fiscal/supply pushing the 10Y toward 5%; bulls wait for cuts to pull it under 4% — both expect a break",
        "us": "Neither break holds: 5% is a proven buyer's ceiling and ~4% a sticky-inflation floor — monetise the range rather than bet on the break",
        "gap": "The market pays up for the tail break in either direction and under-prices the 10Y simply staying boxed around 4.5%"
      },
      "changeMyMind": "A decisive break of the box — a growth scare or sharp disinflation that pulls the 10Y below 4.00% (cuts brought forward), or a fiscal/supply/inflation shock that drives it through 5.00% — either zeros the accrual.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "An enhanced coupon (~7.5% vs ~4% cash) for the 10Y simply staying boxed in — a steady carry pickup with capped, income-style upside rather than an outright duration bet.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated, landed catalyst — the 25-Jun hot PCE and hawkish Fed repricing that cap the 10Y from both ends.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "The higher-for-longer, range-bound-10Y read is broadly shared, but the precise 4.00-4.90% band and the coupon edge are an estimated structuring call.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 2,
            "dq": "sourced",
            "note": "Sourced drivers (PCE 4.1% / core 3.4%, hawkish repricing, cuts to 2027, 10Y ~4.5%) plus a specific two-sided case: a proven 5% buyer's ceiling above and a sticky-PCE / supply term-premium floor below.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core Fixed Income / income house view — paid carry from a boxed-in long end, no outright duration call.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "The crowd is parked in cash and bills or positioned for a 10Y break either way; selling 10Y rate-range optionality for an enhanced coupon is the contrarian income move.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "The 10Y at ~4.45-4.50% mid-range, repeatedly rejected at 5% and bid toward 4% — a well-defined range, the accrual's friend.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 10,
        "maxRaw": 15,
        "score": 67,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "PCE 4.1% / core 3.4%; hawkish repricing; 10Y ~4.5%, capped at 5%",
        "detail": "12-month 10Y Treasury range accrual: ~4.00-4.90% band, ~7.5% p.a. enhanced coupon vs ~4.0% on cash, A-rated issuer, capital at par. Coupon accrues daily for each in-range fixing; forgone on a break above 4.90% or below 4.00%.",
        "source": "sourced",
        "watch": "The 14 Jul CPI, the 29-30 Jul FOMC and Treasury supply/auctions — a shock that drives the 10Y through 5% or under 4% and zeros the accrual."
      },
      "facts": [
        {
          "text": "May PCE re-accelerated to 4.1% headline / core 3.4% (25 Jun); the Fed path repriced hawkish — BofA three hikes, ~68% September-hike odds, cuts pushed to 2027",
          "tag": "sourced"
        },
        {
          "text": "The 10Y Treasury yield sits ~4.45-4.50%; it last peaked near 5.0% in Oct 2023 and has failed at that level on every test since",
          "tag": "sourced"
        },
        {
          "text": "May PCE re-accelerated on the energy shock, keeping an inflation/term premium in long yields",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "CBS / NBC (PCE)",
          "kind": "news"
        },
        {
          "name": "Fortune / CNBC (Fed path, 10Y)",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "energy-tactical",
      "tradeStatement": "Long energy majors (XOM / SHEL) — a tactical hedge that the Hormuz risk premium is underpriced after Brent fell below $75; a bet on a re-escalation tail (a tanker was struck off Oman), held in income-paying majors, not a structural oil-bull call.",
      "intent": "income",
      "name": "Energy — tactical on Hormuz risk",
      "ticker": "",
      "sector": "Energy",
      "assetClass": "Equity",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "moderate",
        "beta": "high",
        "structured": false
      },
      "naturalExpression": "Direct equity",
      "headline": "Brent below $75 as Hormuz flows normalise — but a tanker was just struck off Oman",
      "thesis": "Brent has eased below $75 (down from ~$79, ~40% off the ~$126 April war-peak) as Hormuz oil flows ran at their fastest since the war began and Gulf producers ramped output. The geopolitical premium has largely deflated — but a tanker was struck by a projectile off the coast of Oman, reviving security concerns, and the US-Iran deal is still only an interim framework. Energy majors offer a tactical, income-paying hedge against the deal breaking down — explicitly off the standing house view, a trade rather than a strategic tilt.",
      "themeId": null,
      "offThemeWhy": "There is no standing desk theme on oil — this is a tactical, event-driven idea off Middle-East supply risk, sized as a hedge, not a strategic house view.",
      "structures": [
        "Direct equity",
        "Call overwrite",
        "Thematic basket"
      ],
      "variant": {
        "street": "Prices the interim US-Iran deal as durable; the geopolitical premium has largely deflated as Hormuz flows normalise",
        "us": "Hold a cheap re-escalation hedge — the market may be too relaxed on the Hormuz tail with the deal only interim and a tanker just struck",
        "gap": "Geopolitical tail risk underpriced now that the premium has bled out"
      },
      "changeMyMind": "The interim US-Iran deal hardening into a durable settlement that keeps the Strait of Hormuz open, removing the re-escalation tail.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "sourced",
            "note": "A ceasefire breakdown could retrace much of the move from ~$126 — a large potential move versus oil's normal range.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "Headline-driven — hinges on the Hormuz / Iran path (a tanker was just struck off Oman) rather than a dated event.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Off-theme tactical; no standing sell-side alignment behind it.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 2,
            "dq": "estimated",
            "note": "Sourced price drivers (Brent <$75 off the ~$126 April peak) and a genuine variant — bet the market has over-priced the interim framework as durable, especially with a fresh tanker incident. Driver and variant yes.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 0,
            "dq": "sourced",
            "note": "Off-theme — explicitly a tactical hedge, not a strategic house view.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "sourced",
            "note": "The geopolitical premium has largely deflated — positioning two-sided, no clear edge.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Brent has rolled hard off the April spike below $75 — chart bearish near-term, which is the point of a contrarian hedge.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 8,
        "maxRaw": 15,
        "score": 53,
        "tier": "Watch",
        "label": "Watchlist",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "Brent <$75 (26 Jun)",
        "detail": "Down from ~$79 a week ago and ~40% off the ~$126 April war-peak (a 4-year high) as Hormuz flows ran at their fastest since the war and producers ramped; a tanker struck off Oman revived the tail, near-term range ~$72-78, still headline-sensitive.",
        "source": "sourced",
        "watch": "Whether the interim US-Iran framework hardens, OPEC+ supply signals, and any Hormuz flare-up."
      },
      "facts": [
        {
          "text": "Brent eased below $75 on 26 Jun, down from ~$79 a week earlier and ~40% off the ~$126 peak on 30 April (a 4-year high during the Iran war)",
          "tag": "sourced"
        },
        {
          "text": "Hormuz oil flows ran at their fastest since the war began, but a tanker was struck by a projectile off Oman, reviving the re-escalation tail while the US-Iran deal stays interim",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "CNBC",
          "kind": "news"
        },
        {
          "name": "Trading Economics",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "fx-usd-hedge",
      "tradeStatement": "Reduce / hedge USD exposure in EUR- and GBP-base books — effectively short the dollar against the home currency — a bet that the post-peak USD weakens into 2026 as the Fed-ECB spread eventually narrows; this is NOT a call on any single pair's spot level, nor specifically a yen- or euro-strength view.",
      "intent": "protect",
      "tickers": [
        "DXY",
        "EURUSD",
        "GBPUSD"
      ],
      "name": "Hedge the USD concentration",
      "ticker": "DXY",
      "sector": "FX",
      "assetClass": "Multi-Asset",
      "bucket": "Preservation",
      "goalType": "protection",
      "riskProfile": {
        "vol": "low",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Currency-hedged sleeve",
      "action": "Hedge",
      "preferredExpression": "Currency-hedged sleeve",
      "headline": "Dollar pushed to ~101.7 then paused on intervention — a prime window to hedge USD-heavy non-dollar books",
      "thesis": "The hot 25-Jun PCE (4.1%) and the more-hawkish Fed repricing drove DXY to ~101.7 (its highest since March-2025) before it eased to ~101.4 Thursday on suspected MoF yen intervention; EUR/USD sits ~1.143 — even as every 2026 bank outlook still calls a post-peak dollar and an eventually-narrowing Fed-ECB spread. For EUR- and GBP-base books carrying outsized USD sleeves, this stretched level — with the first signs of a pause as intervention risk builds — is the window to hedge the currency mismatch: currency-hedged share classes for Retail, FX forwards or zero-cost collars for Professionals — sized to the mismatch, not run as a directional bet.",
      "themeId": "gold",
      "offThemeWhy": null,
      "structures": [
        "Currency-hedged sleeve",
        "FX forward / collar"
      ],
      "variant": {
        "street": "Major-bank consensus is a post-peak dollar — more USD weakness into 2026 as the Fed-ECB rate spread narrows",
        "us": "Same direction; use the hawkish-driven dollar strength (and the first pause) to put hedges on USD-heavy non-dollar books at a better level",
        "gap": "The near-term firm dollar is a hedging gift, not a reason to stay unhedged"
      },
      "changeMyMind": "The Fed out-hiking every other central bank on a sustained inflation overshoot — a structurally higher-for-longer dollar would delay the turn the hedge is sized for.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "A hedge caps a tail (an adverse FX move on a large USD sleeve) rather than chasing a big gain — modest, defined asymmetry.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated and landed: the 25-Jun hot PCE and the dollar's push to ~101.7 then pause on intervention — a concrete window to hedge into.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "Bank 2026 outlooks broadly agree on a post-peak dollar and a narrowing Fed-ECB spread; the firm spot is the confirming signal.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Specific driver (a book's non-base USD %) and a clear variant (hedge into the firmness), but the entry timing is a soft, estimated call.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Direct expression of the Gold & Currency house view — currency diversification for concentrated-USD books.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Dollar longs are crowded after the hawkish repricing and the intervention scare — hedging when the crowd is max-long USD is reasonable timing, not an extreme.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "DXY extended to ~101.7 then paused ~101.4 — mixed; a level to fade rather than chase.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 10,
        "maxRaw": 15,
        "score": 67,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "DXY ~101.4, off a ~101.7 high",
        "detail": "The dollar pushed to ~101.7 (highest since March-2025) on the hawkish 25-Jun PCE before easing to ~101.4 Thursday on suspected MoF intervention (EUR/USD ~1.143); 2026 bank outlooks still describe a post-peak dollar with the Fed-ECB spread set to narrow. USD/JPY has been propelled to ~161.5 by the wide differential.",
        "source": "sourced",
        "watch": "The CPI/PCE path and the Fed-ECB / BOJ rate spreads; any intervention-driven or risk-on turn that tops the dollar."
      },
      "facts": [
        {
          "text": "Major-bank 2026 FX outlooks describe a post-peak dollar, with the Fed-ECB rate spread set to narrow and EUR/USD seen recovering into 2026",
          "tag": "sourced"
        },
        {
          "text": "The hot 25-Jun PCE (4.1%) drove DXY to ~101.7 (highest since March-2025) before it eased to ~101.4 on suspected MoF intervention; EUR/USD ~1.143",
          "tag": "sourced"
        },
        {
          "text": "DXY pushed above 101 in June on the hawkish repricing, an extended level versus the rest-of-year forecast range",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "MUFG Research",
          "kind": "analysis"
        },
        {
          "name": "Trading Economics / TradingView",
          "kind": "news"
        },
        {
          "name": "ING THINK",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "fx-carry-income",
      "tradeStatement": "Earn the carry on the wide US rate differential — effectively long the high-yielding USD versus a low-yielder (JPY / EUR) via dual-currency deposits — a bet that the differential persists and the pair stays range-bound so you collect the coupon; it is NOT a directional spot view, and the worst case is converting into the currency you'd have bought anyway.",
      "intent": "income",
      "tickers": [
        "USDJPY",
        "EURUSD"
      ],
      "name": "FX carry & dual-currency income",
      "ticker": "USDJPY",
      "sector": "FX",
      "assetClass": "Multi-Asset",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "moderate",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Dual-currency deposit (DCD)",
      "action": "Generate income",
      "preferredExpression": "Dual-currency deposit (DCD)",
      "headline": "Monetise the wide rate differential — FX carry and dual-currency income",
      "thesis": "With the front end held high by the hawkish Fed and rate differentials wide, income books can be paid to express a range view on pairs they are happy to hold either side of. Dual-currency deposits and currency-hedged carry turn the differential into an enhanced coupon — you accept conversion at a set rate in return for yield. A Professional, range-bound income tool, not a directional dollar bet — and at 40-year-high USD/JPY with live intervention risk, size the conversion strikes with care.",
      "themeId": "gold",
      "offThemeWhy": null,
      "structures": [
        "Dual-currency deposit (DCD)",
        "FX forward / collar",
        "Currency-hedged sleeve"
      ],
      "variant": {
        "street": "Differentials favour the dollar now; a yen and euro recovery is a 2026 story as the gap narrows",
        "us": "Earn the carry while the differential is wide, on pairs you would hold either side of",
        "gap": "Get paid to wait for the FX moves the house expects later"
      },
      "changeMyMind": "A fast, disorderly dollar reversal — e.g. a large MoF intervention or an abrupt dovish Fed pivot — that compresses the differential and collapses the carry.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Carry is steady coupon income with a defined conversion risk — low, bounded asymmetry by design.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "Soft and ongoing: the hawkish repricing keeps the front end and the differential wide, but there is no single dated trigger.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "The wide US rate differential is a hard, confirmable macro fact and the income angle sits squarely in the house view.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Specific driver (the rate gap) and a clear variant (get paid to wait), but the entry and pair selection are soft, estimated calls.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "On the Gold & Currency house view — currency diversification and income from the rate differential.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Carry trades are well-populated and crowded at the highs — not at a clear unwind extreme, but intervention risk argues for care.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "USD/JPY trends with the differential at 40-year highs — constructive for carry but stretched into intervention territory; mixed.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 9,
        "maxRaw": 15,
        "score": 60,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "US front end ~3.50-3.75%; differential wide, USD/JPY ~161.5",
        "detail": "Hawkish-Fed repricing has widened US rate differentials and propelled USD/JPY to ~161.5 — 40-year highs and the weakest yen since 1986 — with live MoF intervention risk (FinMin Katayama and US Treasury's Bessent agreeing to act if needed); an eventual yen recovery that narrows the gap remains a 2026 story.",
        "source": "sourced",
        "watch": "BOJ/MoF intervention and the ECB path versus the Fed; any sharp differential compression or disorderly intervention that erodes the carry."
      },
      "facts": [
        {
          "text": "Hawkish-Fed repricing has widened US rate differentials, propelling USD/JPY to ~161.5 (26 Jun), 40-year highs and the weakest yen since 1986",
          "tag": "sourced"
        },
        {
          "text": "Japan's FinMin Katayama and US Treasury's Bessent agreed to act on currencies if needed and a suspected intervention hit Thursday, yet the wide differential keeps the carry dominant; a yen recovery remains a 2026 story",
          "tag": "sourced"
        },
        {
          "text": "US front-end policy held in the 3.50-3.75% band, with the hawkish repricing keeping the differential wide",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "FXStreet",
          "kind": "analysis"
        },
        {
          "name": "Mitrade / OCBC",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "tac-usdjpy-strangle",
      "tradeStatement": "Long USD/JPY volatility at the intervention line — buy a 2-4wk strangle (~158 put / ~165 call, ~1.3% total premium) to own the next move either way: a suspected/confirmed MoF intervention or a policy shock could snap it sharply lower, while a dominant carry trade could squeeze it higher through 163. Entry ~161.5, take profit on a break beyond 158 or 165, let it decay / cut if pinned 160-163 (theta).",
      "intent": "add",
      "action": "Buy strangle (long volatility, defined-risk)",
      "preferredExpression": "FX strangle (USD/JPY)",
      "name": "USD/JPY event volatility",
      "ticker": "USD/JPY",
      "sector": "FX",
      "assetClass": "Multi-Asset",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "moderate",
        "structured": false
      },
      "naturalExpression": "FX strangle (USD/JPY)",
      "tactical": true,
      "triggered": true,
      "trigger": "Live on the 26-Jun tape: USD/JPY has pushed to fresh 40-year highs ~161.5-162 — the weakest yen since 1986 and deep in MoF-intervention territory — with Japan's new FinMin Katayama and US Treasury's Bessent agreeing to 'act if necessary' and a SUSPECTED intervention already hitting Thursday (DXY eased off ~101.7). With the BoJ still hike-biased and the carry still dominant, the next move is a genuinely two-sided binary (a further carry-driven melt-up vs a sharp intervention/jawbone snapback), so owning the move either way has a live justification today.",
      "levels": {
        "tenor": "2-4 weeks",
        "entry": "~161.5",
        "target": "break beyond 158 or 165",
        "stop": "theta decay if pinned 160-163"
      },
      "headline": "USD/JPY ~161.5 at 40-year highs with suspected intervention — own the two-sided move with a short-dated strangle",
      "thesis": "USD/JPY has pushed to ~161.5-162 — fresh 40-year highs, the weakest yen since 1986 and squarely in MoF-intervention territory — with a suspected intervention already hitting Thursday and officials (FinMin Katayama, Treasury's Bessent) signalling they will 'act if necessary'. Yet the wide differential keeps the carry trade dominant and the BoJ stays hike-biased. The next move is genuinely two-sided: fresh intervention or a jawbone/policy shock could snap it sharply lower, while if the carry keeps winning it squeezes higher through 163. When you are confident in a big move but not its sign, own the volatility — a 2-4wk strangle (~158 put / ~165 call) profits on a break beyond either wing, with the two premiums as the defined max loss. Take profit on a break beyond 158 or 165; let it decay/expire if spot stays pinned 160-163.",
      "themeId": null,
      "offThemeWhy": "Tactical long-volatility trade around live intervention risk at the highs — non-directional, not the strategic currency house view.",
      "structures": [
        "FX strangle (USD/JPY)",
        "FX straddle",
        "FX puts (USD/JPY)"
      ],
      "variant": {
        "street": "Carry crowd stays directionally long USD/JPY; implied vol underprices the intervention snapback",
        "us": "Own the move either way — the sign is genuinely two-sided at the intervention line, the size is not",
        "gap": "Event vol looks cheap relative to the range of plausible intervention outcomes"
      },
      "changeMyMind": "Spot grinding quietly in 160-163 with no intervention follow-through and no fresh carry leg — theta erodes both premiums.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "estimated",
            "note": "A binary intervention outcome can drive a large move either way for a defined double-premium — strong long-vol asymmetry.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Hard, live trigger — spot at 40-year highs ~161.5 with a suspected intervention Thursday and officials 'ready to act', a two-sided binary now.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Street positions directionally (carry-long); no consensus on the size or timing of the snapback.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Clear long-vol rationale, but the edge depends on implied vol being cheap — a soft, estimated call.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 1,
            "dq": "sourced",
            "note": "Adjacent to the currency house view, expressed as event vol.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Crowded directional positioning raises the odds of an outsized unwind — supportive of long vol.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Spot extended to ~161.5 at the intervention line — stretched and two-sided, consistent with a pending break either way.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 9,
        "maxRaw": 15,
        "score": 60,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "USD/JPY ~161.5 · 40-year highs, intervention zone, two-sided",
        "detail": "Buy a 2-4wk ~158 put / ~165 call strangle (~1.3% total). Take profit beyond 158 or 165; max loss = both premiums if pinned 160-163. Driver: a two-sided binary — fresh MoF intervention vs a carry-driven squeeze higher.",
        "source": "estimated",
        "watch": "MoF intervention follow-through and jawboning, the US-Japan differential, and realised vs implied vol."
      },
      "facts": [
        {
          "text": "USD/JPY pushed to ~161.5-162 on 26 Jun, fresh 40-year highs and the weakest yen since 1986, deep in MoF-intervention territory",
          "tag": "sourced"
        },
        {
          "text": "A suspected MoF intervention hit Thursday and officials (FinMin Katayama, US Treasury's Bessent) signalled they will act if necessary; the BoJ stays hike-biased yet the carry keeps the yen pressured",
          "tag": "sourced"
        },
        {
          "text": "A hawkish-Fed-driven wide US-Japan differential keeps the carry trade dominant and USD/JPY bid",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "FXStreet",
          "kind": "news"
        },
        {
          "name": "Mitrade / OCBC",
          "kind": "analysis"
        },
        {
          "name": "ING THINK",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    }
  ],
  "convictionRubric": {
    "earnings": {
      "model": "earnings",
      "title": "Earnings ideas — print rubric",
      "blurb": "Four pillars, each 0-2 (max 8), scaled to 100. The print-reaction model for the earnings book.",
      "maxRaw": 8,
      "pillars": [
        {
          "key": "asymmetry",
          "label": "Asymmetry signal",
          "max": 2,
          "desc": "Implied straddle move into the print ÷ average absolute realised move over the trailing 4 prints. Materially below 1 (the market is underpricing the event) → 2 · near fair → 1 · implied rich → 0. Wide estimate dispersion can also carry it."
        },
        {
          "key": "consensus",
          "label": "Sell-side consensus",
          "max": 2,
          "desc": "Majority buy / upside to the mean price target / positive last-30-day revisions. All three → 2 · partial → 1 · none or contradicts → 0."
        },
        {
          "key": "catalyst",
          "label": "Catalyst clarity",
          "max": 2,
          "desc": "Pre-print: a dated, unpriced catalyst. Post-print: a reaction disproportionate to print quality. Clear → 2 · soft → 1 · none → 0."
        },
        {
          "key": "positioning",
          "label": "Positioning & sentiment",
          "max": 2,
          "desc": "Short interest >10% of float OR an extreme positioning setup. Extreme → 2 · notable lean → 1 · neutral / unavailable → 0."
        }
      ],
      "bandsNote": "High = raw ≥6/8, no zero pillar, all inputs sourced · High — data gap = the same but ≥1 estimated input · Medium = raw 4-5, or any zero pillar, or consensus unverified · Low = raw <4 or two-plus zeros (excluded)."
    },
    "exEarnings": {
      "model": "exEarnings",
      "title": "Ex-earnings ideas — seven-pillar conviction",
      "blurb": "Seven pillars summed to 15, scaled to 100, on roughly a 70/30 fundamentals-to-technicals split: fundamental thesis and house view lead (11/15 ≈ 73%); technicals and positioning are capped confirmation (4/15 ≈ 27%). High ≥ 75 · Medium ≥ 55 · Watch ≥ 0.",
      "maxRaw": 15,
      "pillars": [
        {
          "key": "asymmetry",
          "label": "Gap / asymmetry",
          "max": 3,
          "desc": "Thesis expected move (entry → target) ÷ the name's normal move over the same horizon. ≥2.0 → 3 · 1.5-2.0 → 2 · 1.0-1.5 → 1 · <1.0 → 0. The thesis target is a soft input → tagged estimated."
        },
        {
          "key": "catalyst",
          "label": "Catalyst",
          "max": 2,
          "desc": "A dated, hard reason it moves soon (earnings, FOMC, CPI, ECB) with a clear trigger → 2 · soft / undated → 1 · none → 0."
        },
        {
          "key": "consensus",
          "label": "Consensus + confirmation",
          "max": 2,
          "desc": "Either sell-side aligned (buy ratio ≥0.6, mean-PT upside, revisions ≥0) OR a defensible variant view, AND an independent signal (breakout / fund flow / options skew). Both legs → 2 · one → 1 · neither → 0. Alignment and a variant edge both count — they don't fight the thesis pillar."
        },
        {
          "key": "thesis",
          "label": "Fundamental thesis",
          "max": 2,
          "desc": "Quality and edge of the underlying view — two checks, each 0/1: (1) driver specificity — named, quantified drivers (a margin/volume/pricing/policy path with numbers) vs narrative; (2) variant view — an articulated, computable gap vs consensus (our number vs the street's); pure consensus-hugging scores 0. Each idea also states the condition that would change our mind (the `changeMyMind` field), surfaced on the tile but not scored. dq is sourced only when the drivers trace to cited facts; an uncited thesis is estimated and trips the Medium cap."
        },
        {
          "key": "houseview",
          "label": "House-view fit",
          "max": 2,
          "desc": "Core desk theme, direct expression → 2 · on-theme / adjacent → 1 · off-theme or cuts against a house view → 0."
        },
        {
          "key": "positioning",
          "label": "Positioning",
          "max": 2,
          "desc": "Confirmation / veto, not a driver. Crowd offside our trade is fuel; crowd already with us is unwind risk — a hard read (SI >10% float / extreme CoT, fund flows) plus a sentiment read (RSI at a crowded extreme). Clearly offside → 2 · neutral / mixed → 1 · clearly with us (unwind risk) → 0."
        },
        {
          "key": "technical",
          "label": "Technical",
          "max": 2,
          "desc": "Confirmation / veto, not a driver. Trend and entry agree with the thesis — 50/100/200-day moving-average alignment, Bollinger entry quality, Fibonacci off the trailing 6-month swing → 2 · mixed → 1 · contradicts → 0."
        }
      ],
      "tiers": [
        {
          "key": "High",
          "min": 75,
          "label": "High conviction"
        },
        {
          "key": "Medium",
          "min": 55,
          "label": "Medium conviction"
        },
        {
          "key": "Watch",
          "min": 0,
          "label": "Watchlist"
        }
      ],
      "bandsNote": "Score = raw ÷ 15 × 100. High ≥75 · Medium ≥55 · Watch ≥0. Data-quality cap: if any pillar's core input is estimated or unverified, the label cannot exceed Medium."
    }
  }
};
