/* AUTO-GENERATED by build_today_focus.py from today_focus.json — do not edit by hand.
   Generated for asOf 2026-06-21. Re-run: python build_today_focus.py */
window.TODAY_FOCUS = {
  "asOf": "2026-06-21",
  "generated": "2026-06-21",
  "sweep": {
    "sources": [
      "Reuters",
      "WSJ",
      "Bloomberg",
      "Yahoo Finance",
      "Seeking Alpha",
      "Barron's"
    ],
    "rule": "A fact is stated only if >=2 independent sources agree. Pending/forward events are kept in the future tense. Every datapoint is tagged sourced or estimated.",
    "note": "Refreshed on the 21-Jun-2026 sweep (US cash markets shut Fri 19-Jun for Juneteenth; last close 18-Jun, reopen Mon 22-Jun). The regime is a dollar melt-up: the FOMC held 3.50-3.75% on 17 Jun but turned hawkish (dots signal a possible hike, no 2026 cuts) on a 4.2% CPI, and DXY broke above 100. The yen collapsed despite the BoJ — it hiked 25bp to 1% on 17 Jun on an energy-inflation shock, yet USD/JPY broke to ~160.80 on 19 Jun (weakest yen since Jul-2024) even after ~$70bn+ of MoF intervention, as the wide differential keeps the carry trade dominant; Tokyo says it 'stands ready to act at any time'. EUR/USD fell to ~1.143 (the 11-Jun ECB hike to 2.25% overwhelmed by Fed hawkishness) and cable to ~1.32. Brent steadied ~$80 (down ~8% on the week) after the 18-Jun interim US-Iran peace framework reopened Hormuz, though Geneva talks were abruptly postponed Friday; gold slipped to ~$4,150 on the strong dollar (third straight weekly fall). Implied moves are options-desk estimates (labelled estimated); consensus figures are flagged where not dual-confirmed."
  },
  "earnings": [
    {
      "id": "mu-fq3",
      "stance": "pre-position",
      "tradeStatement": "Long Micron (MU) into the 24-Jun FQ3 print — bullish on HBM / AI-memory pricing into 2027 — but expressed with a structure (autocall or collar), not naked stock, given the rich implied move.",
      "intent": "protect",
      "name": "Micron Technology",
      "ticker": "MU",
      "sector": "Technology",
      "assetClass": "Equity",
      "bucket": "Growth",
      "headline": "Micron FQ3 — the AI-memory print of the quarter",
      "thesis": "Micron reports fiscal Q3 after the close on 24 June. With HBM sold out for several quarters and 2026 capacity already booked, the print is less about the quarter just gone and more about 2027 pricing and the guide. A hard, dated binary for anyone holding the name — the kind of event you express with a structure rather than naked stock.",
      "themeId": "ai",
      "offThemeWhy": null,
      "structures": [
        "Phoenix autocall",
        "Zero-cost collar",
        "Buffered note",
        "Direct equity"
      ],
      "changeMyMind": "Guidance pointing to 2027 HBM pricing rolling over, or the booked-capacity contracts being renegotiated — the 2027 pricing path, not the quarter just reported, is the thesis.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 0,
            "dq": "estimated",
            "note": "Implied straddle ~8.5% vs ~6.5% average realised over recent prints — the market is paying up for the move, so little edge buying the event.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "estimated",
            "note": "Street broadly constructive on AI-memory; HBM demand underpins above-spot price targets.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Hard dated binary — FQ3 after the close on 24 Jun.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "At/near an all-time high into the print — a notable crowded-long lean, not a short-squeeze setup.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 5,
        "maxRaw": 8,
        "score": 62,
        "tier": "Medium",
        "label": "Medium",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-24",
        "reportWhen": "after close",
        "impliedMovePct": 8.5,
        "impliedSource": "estimated",
        "historicalAvgMovePct": 6.5,
        "historicalSource": "estimated",
        "impliedVsHist": "rich",
        "watch": "2027 HBM pricing and the forward guide — not the quarter just reported."
      },
      "facts": [
        {
          "text": "HBM sold out for several quarters; full-year 2026 HBM capacity booked under binding contracts",
          "tag": "sourced"
        },
        {
          "text": "Stock ~$150, near a 52-week high into the print",
          "tag": "estimated"
        },
        {
          "text": "Q3 guide ~$33.5B revenue (set at the FQ2 print on 18 Mar)",
          "tag": "estimated"
        }
      ],
      "sources": [
        {
          "name": "Barchart",
          "kind": "calendar"
        },
        {
          "name": "GlobeNewswire / Nasdaq",
          "kind": "company"
        },
        {
          "name": "Investing.com",
          "kind": "analysis"
        }
      ],
      "kind": "earnings"
    },
    {
      "id": "fdx-fq4",
      "stance": "pre-position",
      "tradeStatement": "Long FedEx (FDX) into FQ4 — a bet the freight / industrial cycle is inflecting and the DRIVE cost program delivers; a global-trade read-through, not just the single stock.",
      "intent": "add",
      "name": "FedEx",
      "ticker": "FDX",
      "sector": "Industrials",
      "assetClass": "Equity",
      "bucket": "Growth",
      "headline": "FedEx FQ4 — the global-trade bellwether",
      "thesis": "FedEx reports fiscal Q4 on 23 June. As a freight and global-trade bellwether it is a live read on the industrial cycle and tariff drag — useful well beyond the stock itself for any book carrying cyclicals or wanting to size the 'broadening beyond mega-caps' rotation.",
      "themeId": "broaden",
      "offThemeWhy": null,
      "structures": [
        "Direct equity",
        "Call overwrite",
        "Quality basket"
      ],
      "changeMyMind": "The FY27 guide cut on weak freight demand or tariff drag, or the DRIVE cost programme slipping — a deteriorating industrial cycle kills the broadening-rotation read.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Implied ~7% vs ~6% realised — modestly rich into a two-sided guide.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Cheap multiple but ratings are mixed; guidance risk cuts both ways.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated FQ4 on 23 Jun — a live read on the freight / industrial cycle.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Cyclical and sentiment-sensitive, but not at a positioning extreme.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 5,
        "maxRaw": 8,
        "score": 62,
        "tier": "Medium",
        "label": "Medium",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-23",
        "reportWhen": "after close",
        "impliedMovePct": 7.0,
        "impliedSource": "estimated",
        "historicalAvgMovePct": 6.0,
        "historicalSource": "estimated",
        "impliedVsHist": "rich",
        "watch": "FY27 guide, freight demand, DRIVE cost programme and any tariff/trade commentary."
      },
      "facts": [
        {
          "text": "FedEx reports its next (FQ4) results on 23 June",
          "tag": "sourced"
        },
        {
          "text": "Treated as a global-trade / industrial-cycle bellwether",
          "tag": "estimated"
        }
      ],
      "sources": [
        {
          "name": "Investing.com",
          "kind": "calendar"
        },
        {
          "name": "TipRanks",
          "kind": "calendar"
        }
      ],
      "kind": "earnings"
    },
    {
      "id": "nke-fq4",
      "stance": "pre-position",
      "tradeStatement": "Long Nike (NKE) into FQ4 — a single-name turnaround bet (inventory clean-up, China, the wholesale reset), not a sector or consumer-discretionary call.",
      "intent": "add",
      "name": "Nike",
      "ticker": "NKE",
      "sector": "Consumer",
      "assetClass": "Equity",
      "bucket": "Growth",
      "headline": "Nike FQ4 — a single-name turnaround bet",
      "thesis": "Nike reports fiscal Q4 after the close on 30 June. This is a company-specific turnaround story — inventory clean-up, China and the wholesale reset — rather than a desk theme. Lower conviction and off-theme, but a real catalyst for any book with consumer-discretionary exposure.",
      "themeId": null,
      "offThemeWhy": "No standing desk theme on consumer discretionary — this is a single-name turnaround catalyst, judged on its own merit, not a strategic house view.",
      "structures": [
        "Direct equity",
        "Reverse convertible",
        "Cash-secured puts",
        "Buffered note"
      ],
      "changeMyMind": "Gross margins failing to recover or China deteriorating further — the turnaround thesis depends on margin and China inflecting, not the wholesale reset alone.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Implied ~8% vs ~7% realised — modestly rich for a turnaround print.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Street cautious on the multi-quarter reset; no clean buy-side alignment.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated FQ4 after the close on 30 Jun — a real single-name catalyst.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Beaten-down name with some short interest, but the turnaround keeps it from a clean squeeze setup.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 5,
        "maxRaw": 8,
        "score": 62,
        "tier": "Medium",
        "label": "Medium",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-30",
        "reportWhen": "after close",
        "impliedMovePct": 8.0,
        "impliedSource": "estimated",
        "historicalAvgMovePct": 7.0,
        "historicalSource": "estimated",
        "impliedVsHist": "rich",
        "watch": "Gross-margin recovery, China trajectory and the FY27 revenue guide."
      },
      "facts": [
        {
          "text": "Nike reports FQ4 fiscal-2026 results after the close on 30 June",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Nasdaq",
          "kind": "calendar"
        },
        {
          "name": "MarketChameleon",
          "kind": "calendar"
        }
      ],
      "kind": "earnings"
    },
    {
      "id": "orcl-q4-react",
      "stance": "post-print",
      "tradeStatement": "Buy the post-earnings dip in Oracle (ORCL) — a record Q4 (cloud +47%, OCI +93%, AI/RPO backlog surging) sold off ~5–7% purely on capex/funding fear ($55.7B FY26 capex vs a ~$50B guide); the reaction overshoots a thesis that is intact, so fade the drop and accumulate, with a stop below the post-print low.",
      "intent": "add",
      "action": "Buy the dip",
      "preferredExpression": "Direct equity",
      "name": "Oracle",
      "ticker": "ORCL",
      "sector": "Technology",
      "assetClass": "Equity",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "high",
        "structured": false
      },
      "naturalExpression": "Direct equity",
      "headline": "Oracle beat a record quarter — and fell ~5–7% on capex fear. The dip looks buyable.",
      "thesis": "Oracle reported Q4 FY26 on 10 June: record revenue $19.2B (+21%), total cloud $9.9B (+47%) and OCI/IaaS $5.8B (+93%), with non-GAAP EPS $2.11 beating ~$1.89 and FY27 revenue guided to ~$90B on a surging AI/RPO backlog. The stock still fell ~5–7% — entirely on the funding of that growth: FY26 capex hit $55.7B (above the ~$50B guide) and gross margins dipped as data centres ramp. That is a price-reaction, not a thesis break: the capex IS the backlog. Play the post-print overshoot — buy the first-day dip and accumulate, stop below the reaction low; the risk is that AI-capex doubt persists and compresses the multiple further.",
      "themeId": "ai",
      "offThemeWhy": null,
      "structures": [
        "Direct equity",
        "Buffered note",
        "Call spread"
      ],
      "variant": {
        "street": "Analysts raised price targets on the record cloud/RPO print despite the selloff",
        "us": "The capex-driven drop overshoots — accumulate the dip; the buildout funds the backlog",
        "gap": "Market is pricing capex as cost, not as the contracted-revenue engine it backs"
      },
      "changeMyMind": "Evidence the AI-capex isn't converting — RPO/bookings stalling or OCI gross margins deteriorating further rather than ramping — would turn the dip into a value trap.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "A ~5–7% drop on a record beat is a real dip-buy edge, but not a clean misprice — the capex concern is legitimate.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "Sell-side raised price targets after the print; the cloud/RPO trajectory is broadly endorsed.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated, just-landed reaction (10 Jun) — a record print sold off, the classic post-print overshoot setup.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "A 5–7% flush clears some weak longs, but AI-capex skeptics remain an overhang — not a washout.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 6,
        "maxRaw": 8,
        "score": 75,
        "tier": "High",
        "label": "High — data gap",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-10",
        "reportWhen": "after close",
        "result": "Beat — record Q4 revenue $19.2B (+21%), total cloud $9.9B (+47%), OCI $5.8B (+93%); non-GAAP EPS $2.11 vs ~$1.89 est; FY27 revenue guided ~$90B",
        "resultSource": "sourced",
        "reaction": "Shares fell ~5–7% after the print despite the beat — FY26 capex $55.7B (above the ~$50B guide) and margin/funding concerns",
        "reactionSource": "sourced",
        "watch": "OCI backlog/RPO conversion, the capex trajectory and whether gross margins recover as data centres ramp."
      },
      "facts": [
        {
          "text": "Oracle reported Q4 FY26 on 10 Jun 2026: record revenue $19.2B (+21%), total cloud $9.9B (+47%), OCI/IaaS $5.8B (+93%)",
          "tag": "sourced"
        },
        {
          "text": "Non-GAAP EPS $2.11 beat consensus ~$1.89; FY27 revenue guided ~$90B with Q1 FY27 cloud +57–63% in constant currency",
          "tag": "sourced"
        },
        {
          "text": "Shares fell ~5–7% after the print on FY26 capex of $55.7B (above the ~$50B guide) and margin concerns",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Reuters / CNBC",
          "kind": "news"
        },
        {
          "name": "Oracle Investor Relations",
          "kind": "company"
        },
        {
          "name": "Investing.com / TradingKey",
          "kind": "analysis"
        }
      ],
      "kind": "earnings"
    },
    {
      "id": "adbe-q2-react",
      "stance": "post-print",
      "tradeStatement": "Don't chase Adobe (ADBE) on the post-print dip — Q2 beat with AI-first ARR tripling past $500M, but the stock fell ~5.5% on the CFO's departure layered onto the open CEO search; play the reaction cautiously with a defined-risk re-entry (buffered note, or cash-secured puts into a lower strike), not a naked add, until leadership clarity.",
      "intent": "add",
      "action": "Wait / defined-risk entry",
      "preferredExpression": "Buffered note",
      "name": "Adobe",
      "ticker": "ADBE",
      "sector": "Technology",
      "assetClass": "Equity",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "high",
        "structured": false
      },
      "naturalExpression": "Buffered note",
      "headline": "Adobe beat and AI ARR tripled — but a CFO exit sent it down ~5.5%. Don't chase the dip.",
      "thesis": "Adobe reported Q2 FY26 on 11 June: record revenue $6.62B (beating ~$6.46–6.58B), non-GAAP EPS $5.96 (beating ~$5.82–5.94), AI-first ARR tripled YoY past $500M, and full-year targets were raised. Yet the stock fell ~5.5% — CFO Dan Durn's departure (effective 15 June) opened a second top-seat vacancy alongside the ongoing CEO search, and the beats were modest against an elevated bar. Unlike a clean capex-overshoot dip, this selloff carries an unresolved governance overhang. Play the reaction with discipline: don't chase the relief bounce — express a defined-risk re-entry (a buffered note, or cash-secured puts struck lower to get paid to wait), and size up only once leadership clarity lands.",
      "themeId": "ai",
      "offThemeWhy": null,
      "structures": [
        "Buffered note",
        "Cash-secured puts",
        "Direct equity"
      ],
      "variant": {
        "street": "Bulls point to tripling AI ARR and raised guidance as proof the AI monetisation is working",
        "us": "The operating story is fine, but a CFO+CEO vacuum is a real de-rating risk — wait, don't chase",
        "gap": "Market may under-price how long a dual leadership vacancy weighs on the multiple"
      },
      "changeMyMind": "A credible permanent CEO/CFO appointment (removing the overhang), or AI-first ARR growth clearly re-accelerating, would turn this from wait-and-see into an add.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Beat but sold off — the dip is tempting, yet the leadership overhang caps the clean-misprice case.",
            "label": "Asymmetry signal",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Sell-side constructive on AI ARR, but the beat was modest vs a high bar and the management vacuum splits views.",
            "label": "Sell-side consensus",
            "max": 2
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated, just-landed reaction (11 Jun) — a beat overshadowed by the CFO exit; a clear post-print setup.",
            "label": "Catalyst clarity",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "The leadership vacuum is unresolved — not a washed-out, contrarian-buy setup.",
            "label": "Positioning & sentiment",
            "max": 2
          }
        ],
        "raw": 5,
        "maxRaw": 8,
        "score": 62,
        "tier": "Medium",
        "label": "Medium",
        "capped": true,
        "model": "earnings"
      },
      "earnings": {
        "reportDate": "2026-06-11",
        "reportWhen": "after close",
        "result": "Beat — record revenue $6.62B (vs ~$6.46–6.58B), non-GAAP EPS $5.96 (vs ~$5.82–5.94); AI-first ARR tripled YoY past $500M; FY targets raised",
        "resultSource": "sourced",
        "reaction": "Shares fell ~5.5% after-hours — CFO Dan Durn's exit (effective 15 Jun) atop the open CEO search; beats modest vs a high bar",
        "reactionSource": "sourced",
        "watch": "Leadership clarity (permanent CFO/CEO), AI-first ARR durability, and whether the de-rating finds support."
      },
      "facts": [
        {
          "text": "Adobe reported Q2 FY26 on 11 Jun 2026: record revenue $6.62B (beat ~$6.46–6.58B), non-GAAP EPS $5.96 (beat ~$5.82–5.94)",
          "tag": "sourced"
        },
        {
          "text": "AI-first ARR tripled YoY to over $500M; full-year revenue and EPS targets were raised",
          "tag": "sourced"
        },
        {
          "text": "Shares fell ~5.5% after-hours on CFO Dan Durn's departure (effective 15 Jun) atop the CEO search, with beats modest vs elevated expectations",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Adobe Investor Relations (8-K)",
          "kind": "company"
        },
        {
          "name": "Business Wire",
          "kind": "news"
        },
        {
          "name": "TechTimes / Investing.com",
          "kind": "analysis"
        }
      ],
      "kind": "earnings"
    }
  ],
  "exEarnings": [
    {
      "id": "gold-pullback",
      "tradeStatement": "Long gold (XAU) — accumulate the pullback as strategic ballast; a bet on continued central-bank buying and currency debasement, sized to the protection gap, not a tactical momentum trade.",
      "intent": "protect",
      "tickers": [
        "XAU",
        "GLD",
        "4GLD",
        "GDX",
        "IAU",
        "GLDM"
      ],
      "name": "Gold — accumulate the pullback",
      "ticker": "XAU",
      "sector": "Gold",
      "assetClass": "Commodity",
      "bucket": "Preservation",
      "headline": "Gold ~$4,150 on a strong-dollar pullback while central banks keep buying",
      "thesis": "Gold has pulled back to about $4,150 — roughly 26% below its January record — on a third straight weekly decline as the hawkish Fed and a DXY above 100 weigh on it near-term. The strategic case is unchanged: central banks stay net buyers and every major bank's year-end target sits well above spot. For under-protected books the dollar-driven dip is a better accumulation window in the cleanest debasement hedge — sized to the protection gap, not chased.",
      "themeId": "gold",
      "offThemeWhy": null,
      "structures": [
        "Physical / ETC",
        "Gold accumulator",
        "Capital-protected note"
      ],
      "variant": {
        "street": "Every major bank bullish — year-end targets 25-44% above spot; central banks net buyers",
        "us": "Same direction — accumulate the pullback into under-protected books",
        "gap": null
      },
      "changeMyMind": "Central banks turning net sellers for two consecutive quarters, or real yields breaking decisively higher.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "estimated",
            "note": "Bank targets 25-44% above spot versus gold's normal trailing move — roughly a 1.5-2x asymmetry to the upside.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "No single dated catalyst — a structural accumulation on a price pullback.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "Every major bank's year-end target sits above spot and central banks are net buyers — sell-side and flow both confirm.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Driver specificity yes (sourced central-bank tonnage and named bank targets), but no variant edge — this is the consensus call, not a differentiated one. A well-supported follow, not a thesis with an edge.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core to the Gold & Currency house view as strategic ballast.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "~25% off the highs with positioning reset — neither washed-out nor crowded; mild fuel.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Below the January high near-term, but the long-term uptrend (above the rising 200-day) is intact — confirms on balance.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 10,
        "maxRaw": 15,
        "score": 67,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "Spot ~$4,150 (19 Jun)",
        "detail": "~26% below the 28-Jan record of $5,589; a third straight weekly decline as DXY broke above 100 and the Fed turned hawkish; central banks net +244t in Q1 and +17t in April; China adding for 18 straight months.",
        "source": "sourced",
        "watch": "The strong dollar / hawkish Fed path as the near-term headwind; central-bank demand as the marginal buyer underpinning the dip."
      },
      "facts": [
        {
          "text": "Gold ~$4,150 on 19 Jun, about 26% below the 28-Jan all-time high of $5,589; third consecutive weekly decline on the strong dollar",
          "tag": "sourced"
        },
        {
          "text": "Central banks net buyers: +244t in Q1 2026, +17t in April; China 18 consecutive months",
          "tag": "sourced"
        },
        {
          "text": "Bank year-end targets: Goldman $5,400, JPMorgan ~$6,000, Morgan Stanley $5,200, UBS $5,500",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "World Gold Council",
          "kind": "data"
        },
        {
          "name": "JPMorgan Research",
          "kind": "analysis"
        },
        {
          "name": "Capital.com",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "ai-power",
      "tradeStatement": "Long the power & grid build-out (utilities, gas, nuclear) — a lower-beta way to be long the AI theme that pays contracted income; a bet on structural datacenter electricity demand, not on interest rates.",
      "intent": "income",
      "name": "AI power & the grid",
      "ticker": "",
      "sector": "Utilities",
      "assetClass": "Equity",
      "bucket": "Income",
      "headline": "Electricity is the binding constraint on AI",
      "thesis": "Datacenter electricity demand is on track for roughly 1,050 TWh in 2026 — doubling in a few years — with gas and nuclear the dispatchable supply. Owning the power and grid build-out is the lower-beta way to stay long the AI theme, and it pays contracted income while it compounds.",
      "themeId": "power",
      "offThemeWhy": null,
      "structures": [
        "Utility basket",
        "Thematic basket",
        "HALO basket (ACM+)"
      ],
      "variant": {
        "street": "Crowds the AI chip names to own the theme",
        "us": "Own the power and grid bottleneck instead — lower-beta, contracted income, still under-owned",
        "gap": "The market pays up for compute and underprices the electricity constraint behind it"
      },
      "changeMyMind": "Datacenter load-growth forecasts being cut, or utility rate-base and PPA approvals stalling.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "estimated",
            "note": "Datacenter power demand roughly doubling — a large structural move versus the sector's normal drift.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "A structural demand story rather than a single dated event.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "IEA data and some sell-side support, but no independent breakout / flow confirmation yet.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 2,
            "dq": "estimated",
            "note": "Quantified driver (IEA: datacenter load ~1,050 TWh, roughly doubling) and a real variant — own the power bottleneck rather than the crowded chips. Driver yes, variant yes.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core Power & Infrastructure house view.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 2,
            "dq": "estimated",
            "note": "Still under-owned versus the chip names — the crowd is clearly not yet with us, which is fuel.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Multi-year rate-base and load growth; the trend is constructive but there's no clean breakout off the moving averages yet — mixed.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 11,
        "maxRaw": 15,
        "score": 73,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "~1,050 TWh datacenter demand by 2026",
        "detail": "IEA projects datacenter electricity use approaching ~1,050 TWh by 2026; dispatchable gas and nuclear lead the supply, with SMRs entering after 2030.",
        "source": "sourced",
        "watch": "Utility rate-base approvals, datacenter PPAs and nuclear/SMR newsflow."
      },
      "facts": [
        {
          "text": "IEA: datacenter electricity use approaching ~1,050 TWh by 2026, more than double recent levels",
          "tag": "sourced"
        },
        {
          "text": "Gas and nuclear are the dispatchable supply; SMRs enter the mix after 2030",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "IEA — Energy & AI",
          "kind": "data"
        },
        {
          "name": "Morgan Stanley",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "lock-yields",
      "tradeStatement": "Long high-quality duration — extend from cash / bills into 5–10y govt / IG to lock ~4.4% yields; a bet that carry plus eventual cuts beats cash, accepting mark-to-market risk while the Fed stays hawkish.",
      "intent": "income",
      "name": "Quality carry — get paid to wait",
      "ticker": "",
      "sector": "Rates",
      "assetClass": "Fixed Income",
      "bucket": "Income",
      "headline": "The Fed held but turned hawkish — own the carry, not the convexity",
      "thesis": "The FOMC held at 3.50-3.75% on 17 June, but the dots turned hawkish in Warsh's first meeting — the median now points to a possible hike and no cuts in 2026, with the easing cycle pushed into 2027 on a 4.2% energy-driven CPI. The 'extend before the cuts' convexity trade is gone for now; the case left is simpler and still good — you are paid ~4.5% in high-quality intermediate bonds to wait, ballast that cash can't give a book with equities at all-time highs. Add duration for income and diversification, not for a near-term rally.",
      "themeId": "duration",
      "offThemeWhy": null,
      "structures": [
        "Bond ladder",
        "Govt / IG bonds",
        "Extend duration"
      ],
      "variant": {
        "street": "The hawkish hold backs up yields; the Street is split between higher-for-longer and a 2027 pivot",
        "us": "Own quality carry now — 4.5% is paid ballast; don't bank on near-term cuts",
        "gap": "The market may still be too optimistic on the timing of the first cut"
      },
      "changeMyMind": "Inflation rolling back toward target (pulling the first cut forward), or the Fed actually hiking — either end of the barbell breaks the carry case.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Earning ~4.5% with cuts now a 2027 story — a carry trade with limited near-term convexity, a modest expected move versus normal bond ranges.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "The 17 Jun FOMC has passed; the next dated catalyst (29-30 Jul FOMC, 14 Jul CPI) is weeks out — structural, not imminent.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "sourced",
            "note": "The hold is sourced fact, but the Street is now split on the path — alignment is weaker than before the meeting.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "sourced",
            "note": "Quantified, sourced drivers (held 3.50-3.75%, hawkish dots, 4.2% CPI), but mostly the consensus read — a modest variant on cut timing.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core Fixed Income house view — quality income and ballast, even with the cut delayed.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "sourced",
            "note": "The crowd is still parked in cash and bills; extending is the contrarian-leaning move.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "10Y backed up to ~4.5% on the hawkish hold; the price trend is mixed — neutral-to-confirming for a carry buyer.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 8,
        "maxRaw": 15,
        "score": 53,
        "tier": "Watch",
        "label": "Watchlist",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "FOMC held 3.50-3.75%; hawkish dots, no 2026 cuts",
        "detail": "The 16-17 June meeting (Warsh's first as Chair) held the target range, but the dot plot shifted up: the median now implies a possible hike and zero cuts this year, pushing easing into 2027. 10Y backed up to ~4.5%.",
        "source": "sourced",
        "watch": "The 14 Jul CPI and the 29-30 Jul FOMC — whether the energy-led inflation spike fades or hardens the hawkish path."
      },
      "facts": [
        {
          "text": "FOMC held at 3.50-3.75% on 17 June (Warsh's first meeting as Chair) — fourth consecutive hold",
          "tag": "sourced"
        },
        {
          "text": "The June dot plot turned hawkish: median end-2026 ~3.8%, implying a possible hike and no cuts in 2026; easing pushed to 2027",
          "tag": "sourced"
        },
        {
          "text": "May CPI re-accelerated to 4.2% y/y on an energy shock (core 2.9%); 10Y near 4.5%",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Federal Reserve / FOMC",
          "kind": "data"
        },
        {
          "name": "CNBC / Reuters",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "rate-range-accrual",
      "tradeStatement": "Buy a ~12-month 10-year Treasury range accrual note — earn an enhanced ~7.5% p.a. coupon (vs ~4.0% on cash) for each day the 10Y yield fixes inside a 4.00–4.90% band; with the 10Y at ~4.5% you are paid to hold the view that a hawkish-hold Fed keeps the long end boxed below the proven 5% ceiling, forgoing the coupon only on a decisive break above 4.90% or below 4.00%.",
      "intent": "income",
      "action": "Generate income",
      "preferredExpression": "Range accrual note",
      "name": "10Y range accrual",
      "ticker": "US 10Y",
      "sector": "Rates",
      "assetClass": "Fixed Income",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "low",
        "beta": "low",
        "structured": true
      },
      "naturalExpression": "Range accrual note",
      "trigger": "This week's hawkish FOMC hold (17-Jun, Warsh's first meeting, dot-plot up, cuts pushed toward 2027) caps the 10Y from both sides — no cuts to rally it under 4%, a policy rate anchored on hold to stop it running through 5% — exactly the boxed-in regime a range accrual is paid to harvest, with the 10Y holding ~4.5% mid-range as DXY broke above 100.",
      "headline": "The hawkish hold boxes the 10Y below 5% — get paid an enhanced coupon to hold the range",
      "thesis": "The FOMC held at 3.50-3.75% on 17 June with hawkish dots (a possible hike, no 2026 cuts, easing pushed to 2027) — a stance that boxes in the 10Y from both sides, with the 10Y at ~4.5% sitting mid-range. The TOP of the band is the harder call and the case is specific: 5% has been a proven ceiling — the 10Y peaked near 5.0% in October 2023 and has failed there on every test since, because at ~5% nominal (~2%+ real) duration is the cheapest in two decades and each approach draws heavy real-money buying — pensions and insurers matching liabilities, foreign reserve managers, and asset allocators rotating out of richly-valued equities. A Fed on hold (its next move a cut, not a hike) means the long end has no hiking cycle to un-anchor it, so it cannot sustainably run through 5% without the front end leading. The BOTTOM (~4.00%) is held by sticky inflation — May CPI re-accelerated to 4.2% (core 2.9%) on the energy shock — plus no cuts until 2027 to fuel a rally and an elevated term premium on heavy Treasury supply, all of which keep a floor under long yields. So a 12-month 10Y range accrual pays an enhanced ~7.5% p.a. coupon (vs ~4.0% on cash) for each day the yield fixes inside 4.00–4.90%: you are paid to hold the boxed-in view, with the coupon forgone only on the days it breaks out. Capital is returned at par at maturity (issuer credit aside) — more than cash without an outright duration bet.",
      "themeId": "duration",
      "offThemeWhy": null,
      "structures": [
        "Range accrual note",
        "Reverse convertible",
        "Current-coupon ladder",
        "T-bill / muni ladder"
      ],
      "variant": {
        "street": "Bears see fiscal/supply pushing the 10Y toward 5%; bulls wait for cuts to pull it under 4% — both expect a break",
        "us": "Neither break holds: 5% is a proven buyer's ceiling and ~4% a sticky-inflation floor — monetise the range rather than bet on the break",
        "gap": "The market pays up for the tail break in either direction and under-prices the 10Y simply staying boxed around 4.5%"
      },
      "changeMyMind": "A decisive break of the box — a growth scare or sharp disinflation that pulls the 10Y below 4.00% (cuts brought forward), or a fiscal/supply/inflation shock that drives it through 5.00% — either zeros the accrual.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "An enhanced coupon (~7.5% vs ~4% cash) for the 10Y simply staying boxed in — a steady carry pickup with capped, income-style upside rather than an outright duration bet.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated, landed catalyst — the 17 Jun FOMC hawkish hold (dots up, cuts to 2027) that caps the 10Y from both ends.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "The higher-for-longer, range-bound-10Y read is broadly shared, but the precise 4.00–4.90% band and the coupon edge are an estimated structuring call.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 2,
            "dq": "sourced",
            "note": "Sourced drivers (held 3.50-3.75%, hawkish dots, cuts to 2027, 4.2% CPI, 10Y ~4.5%) plus a specific two-sided case: a proven 5% buyer's ceiling above and a sticky-CPI / supply term-premium floor below.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Core Fixed Income / income house view — paid carry from a boxed-in long end, no outright duration call.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "The crowd is parked in cash and bills or positioned for a 10Y break either way; selling 10Y rate-range optionality for an enhanced coupon is the contrarian income move.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "The 10Y at ~4.5% mid-range, repeatedly rejected at 5% and bid toward 4% — a well-defined range, the accrual's friend.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 10,
        "maxRaw": 15,
        "score": 67,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "FOMC held 3.50-3.75%; hawkish dots; 10Y ~4.5%, capped at 5%",
        "detail": "12-month 10Y Treasury range accrual: ~4.00–4.90% band, ~7.5% p.a. enhanced coupon vs ~4.0% on cash, A-rated issuer, capital at par. Coupon accrues daily for each in-range fixing; forgone on a break above 4.90% or below 4.00%.",
        "source": "sourced",
        "watch": "The 14 Jul CPI, the 29-30 Jul FOMC and Treasury supply/auctions — a shock that drives the 10Y through 5% or under 4% and zeros the accrual."
      },
      "facts": [
        {
          "text": "FOMC held at 3.50-3.75% on 17 June (Warsh's first meeting as Chair); the June dots turned hawkish — a possible hike, no 2026 cuts, easing pushed to 2027",
          "tag": "sourced"
        },
        {
          "text": "The 10Y Treasury yield backed up to ~4.5% on the hawkish hold; it last peaked near 5.0% in Oct 2023 and has failed at that level on every test since",
          "tag": "sourced"
        },
        {
          "text": "May CPI re-accelerated to 4.2% y/y (core 2.9%) on an energy shock, keeping an inflation/term premium in long yields",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Federal Reserve / FOMC",
          "kind": "data"
        },
        {
          "name": "CNBC / Reuters",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "energy-tactical",
      "tradeStatement": "Long energy majors (XOM / SHEL) — a tactical hedge that the Hormuz risk premium is underpriced after Brent fell to ~$79; a bet on a re-escalation tail, held in income-paying majors, not a structural oil-bull call.",
      "intent": "income",
      "name": "Energy — tactical on Hormuz risk",
      "ticker": "",
      "sector": "Energy",
      "assetClass": "Equity",
      "bucket": "Income",
      "headline": "Brent ~$80 as the Iran framework reopens Hormuz — but Geneva talks just stalled",
      "thesis": "Brent has steadied around $80 (down ~8% on the week, ~36% off the ~$126 April war-peak) after an interim US-Iran peace framework signed 18 Jun began reopening the Strait of Hormuz and restoring Iranian exports. The geopolitical premium has largely deflated — but Geneva talks to harden the framework were abruptly postponed on 20 Jun, so the re-escalation tail is still live. Energy majors offer a tactical, income-paying hedge against the deal breaking down — explicitly off the standing house view, a trade rather than a strategic tilt.",
      "themeId": null,
      "offThemeWhy": "There is no standing desk theme on oil — this is a tactical, event-driven idea off Middle-East supply risk, sized as a hedge, not a strategic house view.",
      "structures": [
        "Direct equity",
        "Call overwrite",
        "Thematic basket"
      ],
      "variant": {
        "street": "Prices the interim US-Iran deal as durable; the geopolitical premium has largely deflated",
        "us": "Hold a cheap re-escalation hedge — the market may be too relaxed on the Hormuz tail with the deal only interim",
        "gap": "Geopolitical tail risk underpriced now that the premium has bled out"
      },
      "changeMyMind": "The interim US-Iran deal hardening into a durable settlement that keeps the Strait of Hormuz open, removing the re-escalation tail.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "sourced",
            "note": "A ceasefire breakdown could retrace much of the move from ~$126 — a large potential move versus oil's normal range.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "Headline-driven — hinges on the Hormuz / Iran path rather than a dated event.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Off-theme tactical; no standing sell-side alignment behind it.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 2,
            "dq": "estimated",
            "note": "Sourced price drivers (Brent ~$80 off the ~$126 April peak) and a genuine variant — bet the market has over-priced the interim framework as durable, especially with Geneva talks stalled. Driver and variant yes.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 0,
            "dq": "sourced",
            "note": "Off-theme — explicitly a tactical hedge, not a strategic house view.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "sourced",
            "note": "The geopolitical premium has largely deflated — positioning two-sided, no clear edge.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Brent has rolled hard off the April spike toward three-month lows — chart bearish near-term, which is the point of a contrarian hedge.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 8,
        "maxRaw": 15,
        "score": 53,
        "tier": "Watch",
        "label": "Watchlist",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "Brent ~$80.6 (20 Jun)",
        "detail": "Down ~8% on the week and ~36% off the ~$126 April war-peak (a 4-year high) as an interim US-Iran framework reopened the Strait of Hormuz and restored Iranian exports; near-term range ~$75-82, still headline-sensitive after Geneva talks were postponed on 20 Jun.",
        "source": "sourced",
        "watch": "Whether the interim US-Iran framework hardens (Geneva talks resuming), OPEC+ supply signals, and any Hormuz flare-up."
      },
      "facts": [
        {
          "text": "Brent ~$80.6 on 20 Jun, down ~8% on the week and ~36% off the ~$126 peak on 30 April (a 4-year high during the Iran war)",
          "tag": "sourced"
        },
        {
          "text": "An interim US-Iran peace framework (18 Jun) reopened the Strait of Hormuz; Geneva talks to harden it were abruptly postponed on 20 Jun, keeping a re-escalation tail",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Reuters / CNBC",
          "kind": "news"
        },
        {
          "name": "Al Jazeera / TradingEconomics",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "fx-usd-hedge",
      "tradeStatement": "Reduce / hedge USD exposure in EUR- and GBP-base books — effectively short the dollar against the home currency — a bet that the post-peak USD weakens into 2026 as the Fed-ECB spread narrows; this is NOT a call on any single pair's spot level, nor specifically a yen- or euro-strength view.",
      "intent": "protect",
      "tickers": [
        "DXY",
        "EURUSD",
        "GBPUSD"
      ],
      "name": "Hedge the USD concentration",
      "ticker": "DXY",
      "sector": "FX",
      "assetClass": "Multi-Asset",
      "bucket": "Preservation",
      "goalType": "protection",
      "riskProfile": {
        "vol": "low",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Currency-hedged sleeve",
      "action": "Hedge",
      "preferredExpression": "Currency-hedged sleeve",
      "headline": "Dollar broke DXY 100 on the hawkish hold — a prime window to hedge USD-heavy non-dollar books",
      "thesis": "The hawkish 17-Jun FOMC hold and the 4.2% May CPI have driven the dollar higher, with DXY breaking above 100 and EUR/USD down to ~1.143 — even as every 2026 bank outlook still calls a post-peak dollar and a narrowing Fed-ECB spread that should weaken it into next year. For EUR- and GBP-base books carrying outsized USD sleeves, this stronger level is the window to hedge the currency mismatch — currency-hedged share classes for Retail, FX forwards or zero-cost collars for Professionals — sized to the mismatch, not run as a directional bet.",
      "themeId": "gold",
      "offThemeWhy": null,
      "structures": [
        "Currency-hedged sleeve",
        "FX forward / collar"
      ],
      "variant": {
        "street": "Major-bank consensus is a post-peak dollar — more USD weakness into 2026 as the Fed-ECB rate spread narrows",
        "us": "Same direction; use the hawkish-hold firmness to put hedges on USD-heavy non-dollar books at a better level",
        "gap": "The near-term firm dollar is a hedging gift, not a reason to stay unhedged"
      },
      "changeMyMind": "The Fed out-hiking every other central bank on a sustained CPI overshoot — a structurally higher-for-longer dollar would delay the turn the hedge is sized for.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "A hedge caps a tail (an adverse FX move on a large USD sleeve) rather than chasing a big gain — modest, defined asymmetry.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Dated and landed: the 17-Jun hawkish hold and the 4.2% May CPI have firmed the dollar — a concrete window to hedge into.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "Bank 2026 outlooks broadly agree on a post-peak dollar and a narrowing Fed-ECB spread; the firm spot is the confirming signal.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Specific driver (a book's non-base USD %) and a clear variant (hedge into the firmness), but the entry timing is a soft, estimated call.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "Direct expression of the Gold & Currency house view — currency diversification for concentrated-USD books.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Dollar longs are crowded after the hawkish repricing — hedging when the crowd is max-long USD is reasonable timing, not an extreme.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "DXY firm but extended within a ~93-100 range — mixed; a level to fade rather than chase.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 10,
        "maxRaw": 15,
        "score": 67,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "DXY >100, broke higher",
        "detail": "The dollar broke above DXY 100 on the hawkish 17-Jun hold and the 4.2% May CPI (EUR/USD ~1.143), but 2026 bank outlooks still describe a post-peak dollar with the Fed-ECB spread set to narrow (EUR/USD seen ~1.15-1.22); USD/JPY has been propelled to ~160.8 by the wider differential.",
        "source": "sourced",
        "watch": "The CPI path and the Fed-ECB / BOJ rate spreads; any US-Iran ceasefire-driven risk-on that turns the dollar."
      },
      "facts": [
        {
          "text": "Major-bank 2026 FX outlooks describe a post-peak dollar, with the Fed-ECB rate spread set to narrow and EUR/USD seen in the ~1.15-1.22 area",
          "tag": "sourced"
        },
        {
          "text": "The hawkish 17-Jun FOMC hold and re-accelerated 4.2% May CPI have driven the dollar higher, with DXY breaking above 100 and EUR/USD down to ~1.143",
          "tag": "sourced"
        },
        {
          "text": "DXY broke above 100 in June (forecast ~93-100 across the rest of the year)",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "MUFG Research",
          "kind": "analysis"
        },
        {
          "name": "ABN AMRO",
          "kind": "analysis"
        },
        {
          "name": "Reuters / FXStreet",
          "kind": "news"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "fx-carry-income",
      "tradeStatement": "Earn the carry on the wide US rate differential — effectively long the high-yielding USD versus a low-yielder (JPY / EUR) via dual-currency deposits — a bet that the differential persists and the pair stays range-bound so you collect the coupon; it is NOT a directional spot view, and the worst case is converting into the currency you'd have bought anyway.",
      "intent": "income",
      "tickers": [
        "USDJPY",
        "EURUSD"
      ],
      "name": "FX carry & dual-currency income",
      "ticker": "USDJPY",
      "sector": "FX",
      "assetClass": "Multi-Asset",
      "bucket": "Income",
      "goalType": "yield",
      "riskProfile": {
        "vol": "moderate",
        "beta": "low",
        "structured": false
      },
      "naturalExpression": "Dual-currency deposit (DCD)",
      "action": "Generate income",
      "preferredExpression": "Dual-currency deposit (DCD)",
      "headline": "Monetise the wide rate differential — FX carry and dual-currency income",
      "thesis": "With the front end held high by the hawkish Fed and rate differentials wide, income books can be paid to express a range view on pairs they are happy to hold either side of. Dual-currency deposits and currency-hedged carry turn the differential into an enhanced coupon — you accept conversion at a set rate in return for yield. A Professional, range-bound income tool, not a directional dollar bet.",
      "themeId": "gold",
      "offThemeWhy": null,
      "structures": [
        "Dual-currency deposit (DCD)",
        "FX forward / collar",
        "Currency-hedged sleeve"
      ],
      "variant": {
        "street": "Differentials favour the dollar now; a yen and euro recovery is a 2026 story as the gap narrows",
        "us": "Earn the carry while the differential is wide, on pairs you would hold either side of",
        "gap": "Get paid to wait for the FX moves the house expects later"
      },
      "changeMyMind": "A fast, disorderly dollar reversal — e.g. an abrupt dovish Fed pivot — that compresses the differential and collapses the carry.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 1,
            "dq": "estimated",
            "note": "Carry is steady coupon income with a defined conversion risk — low, bounded asymmetry by design.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 1,
            "dq": "sourced",
            "note": "Soft and ongoing: the hawkish hold keeps the front end and the differential wide, but there is no single dated trigger.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 2,
            "dq": "sourced",
            "note": "The wide US rate differential is a hard, confirmable macro fact and the income angle sits squarely in the house view.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Specific driver (the rate gap) and a clear variant (get paid to wait), but the entry and pair selection are soft, estimated calls.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 2,
            "dq": "sourced",
            "note": "On the Gold & Currency house view — currency diversification and income from the rate differential.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Carry trades are well-populated but not at a clear unwind extreme — neutral.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "USD/JPY trends with the differential — constructive for carry but not a clean entry signal; mixed.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 9,
        "maxRaw": 15,
        "score": 60,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "US front end ~3.50-3.75%; differential wide, USD/JPY ~160.8",
        "detail": "Hawkish-Fed repricing has widened US rate differentials and propelled USD/JPY to ~160.8 — and even the BoJ's 17-Jun hike to 1% plus ~$70bn+ of intervention failed to hold the yen, underscoring how dominant the carry is; an eventual yen recovery that narrows the gap remains a 2026 story.",
        "source": "sourced",
        "watch": "BOJ/MoF intervention and the ECB path versus the Fed; any sharp differential compression or disorderly intervention that erodes the carry."
      },
      "facts": [
        {
          "text": "Hawkish-Fed repricing has widened US rate differentials, propelling USD/JPY to ~160.8 (19 Jun), the weakest yen since Jul-2024",
          "tag": "sourced"
        },
        {
          "text": "The BoJ hiked to 1% on 17 Jun and Japan intervened (~$70bn+), yet the yen kept sliding — the carry trade stays dominant; a yen recovery narrowing the differential remains a 2026 story",
          "tag": "sourced"
        },
        {
          "text": "US front-end policy held in the 3.50-3.75% band at the 17-Jun FOMC",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "FOREX.com",
          "kind": "analysis"
        },
        {
          "name": "IG",
          "kind": "analysis"
        },
        {
          "name": "MUFG Research",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    },
    {
      "id": "tac-usdjpy-strangle",
      "tradeStatement": "Long USD/JPY volatility at the intervention line — buy a 2–4wk strangle (~157 put / ~164 call, ~1.3% total premium) to own the next move either way: fresh MoF intervention or a policy/jawbone shock could snap it sharply lower, while a dominant carry trade could squeeze it higher through 162. Entry ~160.8, take profit on a break beyond 157 or 164, let it decay / cut if pinned 159–162 (theta).",
      "intent": "add",
      "action": "Buy strangle (long volatility, defined-risk)",
      "preferredExpression": "FX strangle (USD/JPY)",
      "name": "USD/JPY event volatility",
      "ticker": "USD/JPY",
      "sector": "FX",
      "assetClass": "Multi-Asset",
      "bucket": "Growth",
      "goalType": "appreciation",
      "riskProfile": {
        "vol": "high",
        "beta": "moderate",
        "structured": false
      },
      "naturalExpression": "FX strangle (USD/JPY)",
      "tactical": true,
      "triggered": true,
      "trigger": "USD/JPY broke to ~160.80 on 19 Jun — the weakest yen since Jul-2024 and deep in MoF-intervention territory — even after the BoJ's 17-Jun hike to 1% and ~$70bn+ of intervention failed to hold it; with Tokyo saying it 'stands ready to act at any time', the next move is a genuinely two-sided binary (a further carry-driven melt-up vs a sharp intervention/jawbone snapback) — the live trigger to own the move either way.",
      "levels": {
        "tenor": "2–4 weeks",
        "entry": "~160.8",
        "target": "break beyond 157 or 164",
        "stop": "theta decay if pinned 159–162"
      },
      "headline": "USD/JPY ~160.8 in the intervention zone — own the two-sided move with a short-dated strangle",
      "thesis": "USD/JPY has broken to ~160.80 — the weakest yen since Jul-2024 and squarely in MoF-intervention territory — after the BoJ's 17-Jun hike to 1% and ~$70bn+ of intervention failed to arrest the slide and the wide differential keeps the carry trade dominant. The next move is genuinely two-sided: with Japan 'ready to act at any time', fresh intervention or a jawbone/policy shock could snap it sharply lower, while if the carry keeps winning it squeezes higher through 162. When you are confident in a big move but not its sign, own the volatility — a 2–4wk strangle (~157 put / ~164 call) profits on a break beyond either wing, with the two premiums as the defined max loss. Take profit on a break beyond 157 or 164; let it decay/expire if spot stays pinned 159–162.",
      "themeId": null,
      "offThemeWhy": "Tactical long-volatility trade around live intervention risk at the highs — non-directional, not the strategic currency house view.",
      "structures": [
        "FX strangle (USD/JPY)",
        "FX straddle",
        "FX puts (USD/JPY)"
      ],
      "variant": {
        "street": "Carry crowd stays directionally long USD/JPY; implied vol underprices the intervention snapback",
        "us": "Own the move either way — the sign is genuinely two-sided at the intervention line, the size is not",
        "gap": "Event vol looks cheap relative to the range of plausible intervention outcomes"
      },
      "changeMyMind": "Spot grinding quietly in 159–162 with no intervention and no fresh carry leg — theta erodes both premiums.",
      "conviction": {
        "pillars": [
          {
            "key": "asymmetry",
            "score": 2,
            "dq": "estimated",
            "note": "A binary BoJ outcome can drive a large move either way for a defined double-premium — strong long-vol asymmetry.",
            "label": "Gap / asymmetry",
            "max": 3
          },
          {
            "key": "catalyst",
            "score": 2,
            "dq": "sourced",
            "note": "Hard, live trigger — spot at ~160.8 in the intervention zone with the MoF 'ready to act at any time', a two-sided binary now.",
            "label": "Catalyst",
            "max": 2
          },
          {
            "key": "consensus",
            "score": 1,
            "dq": "estimated",
            "note": "Street positions directionally (carry-long); no consensus on the size or timing of the snapback.",
            "label": "Consensus + confirmation",
            "max": 2
          },
          {
            "key": "thesis",
            "score": 1,
            "dq": "estimated",
            "note": "Clear long-vol rationale, but the edge depends on implied vol being cheap — a soft, estimated call.",
            "label": "Fundamental thesis",
            "max": 2
          },
          {
            "key": "houseview",
            "score": 1,
            "dq": "sourced",
            "note": "Adjacent to the currency house view, expressed as event vol.",
            "label": "House-view fit",
            "max": 2
          },
          {
            "key": "positioning",
            "score": 1,
            "dq": "estimated",
            "note": "Crowded directional positioning raises the odds of an outsized unwind — supportive of long vol.",
            "label": "Positioning",
            "max": 2
          },
          {
            "key": "technical",
            "score": 1,
            "dq": "estimated",
            "note": "Spot extended to ~160.8 at the intervention line — stretched and two-sided, consistent with a pending break either way.",
            "label": "Technical",
            "max": 2
          }
        ],
        "raw": 9,
        "maxRaw": 15,
        "score": 60,
        "tier": "Medium",
        "label": "Medium conviction",
        "capped": true,
        "model": "exEarnings"
      },
      "macro": {
        "metric": "USD/JPY ~160.8 · intervention zone, two-sided",
        "detail": "Buy a 2–4wk ~157 put / ~164 call strangle (~1.3% total). Take profit beyond 157 or 164; max loss = both premiums if pinned 159–162. Driver: a two-sided binary — fresh MoF intervention vs a carry-driven squeeze higher.",
        "source": "estimated",
        "watch": "MoF intervention signals and jawboning, the US-Japan differential, and realised vs implied vol."
      },
      "facts": [
        {
          "text": "USD/JPY broke to ~160.80 on 19 Jun, the weakest yen since Jul-2024, deep in MoF-intervention territory",
          "tag": "sourced"
        },
        {
          "text": "The BoJ hiked to 1% on 17 Jun and Japan intervened (~$70bn+), yet the yen kept sliding; Tokyo says it 'stands ready to act at any time'",
          "tag": "sourced"
        },
        {
          "text": "A hawkish-Fed-driven wide US-Japan differential keeps the carry trade dominant and USD/JPY bid",
          "tag": "sourced"
        }
      ],
      "sources": [
        {
          "name": "Reuters",
          "kind": "news"
        },
        {
          "name": "MUFG Research",
          "kind": "analysis"
        },
        {
          "name": "FOREX.com",
          "kind": "analysis"
        }
      ],
      "kind": "ex-earnings"
    }
  ],
  "convictionRubric": {
    "earnings": {
      "model": "earnings",
      "title": "Earnings ideas — print rubric",
      "blurb": "Four pillars, each 0-2 (max 8), scaled to 100. The print-reaction model for the earnings book.",
      "maxRaw": 8,
      "pillars": [
        {
          "key": "asymmetry",
          "label": "Asymmetry signal",
          "max": 2,
          "desc": "Implied straddle move into the print ÷ average absolute realised move over the trailing 4 prints. Materially below 1 (the market is underpricing the event) → 2 · near fair → 1 · implied rich → 0. Wide estimate dispersion can also carry it."
        },
        {
          "key": "consensus",
          "label": "Sell-side consensus",
          "max": 2,
          "desc": "Majority buy / upside to the mean price target / positive last-30-day revisions. All three → 2 · partial → 1 · none or contradicts → 0."
        },
        {
          "key": "catalyst",
          "label": "Catalyst clarity",
          "max": 2,
          "desc": "Pre-print: a dated, unpriced catalyst. Post-print: a reaction disproportionate to print quality. Clear → 2 · soft → 1 · none → 0."
        },
        {
          "key": "positioning",
          "label": "Positioning & sentiment",
          "max": 2,
          "desc": "Short interest >10% of float OR an extreme positioning setup. Extreme → 2 · notable lean → 1 · neutral / unavailable → 0."
        }
      ],
      "bandsNote": "High = raw ≥6/8, no zero pillar, all inputs sourced · High — data gap = the same but ≥1 estimated input · Medium = raw 4-5, or any zero pillar, or consensus unverified · Low = raw <4 or two-plus zeros (excluded)."
    },
    "exEarnings": {
      "model": "exEarnings",
      "title": "Ex-earnings ideas — seven-pillar conviction",
      "blurb": "Seven pillars summed to 15, scaled to 100, on roughly a 70/30 fundamentals-to-technicals split: fundamental thesis and house view lead (11/15 ≈ 73%); technicals and positioning are capped confirmation (4/15 ≈ 27%). High ≥ 75 · Medium ≥ 55 · Watch ≥ 0.",
      "maxRaw": 15,
      "pillars": [
        {
          "key": "asymmetry",
          "label": "Gap / asymmetry",
          "max": 3,
          "desc": "Thesis expected move (entry → target) ÷ the name's normal move over the same horizon. ≥2.0 → 3 · 1.5-2.0 → 2 · 1.0-1.5 → 1 · <1.0 → 0. The thesis target is a soft input → tagged estimated."
        },
        {
          "key": "catalyst",
          "label": "Catalyst",
          "max": 2,
          "desc": "A dated, hard reason it moves soon (earnings, FOMC, CPI, ECB) with a clear trigger → 2 · soft / undated → 1 · none → 0."
        },
        {
          "key": "consensus",
          "label": "Consensus + confirmation",
          "max": 2,
          "desc": "Either sell-side aligned (buy ratio ≥0.6, mean-PT upside, revisions ≥0) OR a defensible variant view, AND an independent signal (breakout / fund flow / options skew). Both legs → 2 · one → 1 · neither → 0. Alignment and a variant edge both count — they don't fight the thesis pillar."
        },
        {
          "key": "thesis",
          "label": "Fundamental thesis",
          "max": 2,
          "desc": "Quality and edge of the underlying view — two checks, each 0/1: (1) driver specificity — named, quantified drivers (a margin/volume/pricing/policy path with numbers) vs narrative; (2) variant view — an articulated, computable gap vs consensus (our number vs the street's); pure consensus-hugging scores 0. Each idea also states the condition that would change our mind (the `changeMyMind` field), surfaced on the tile but not scored. dq is sourced only when the drivers trace to cited facts; an uncited thesis is estimated and trips the Medium cap."
        },
        {
          "key": "houseview",
          "label": "House-view fit",
          "max": 2,
          "desc": "Core desk theme, direct expression → 2 · on-theme / adjacent → 1 · off-theme or cuts against a house view → 0."
        },
        {
          "key": "positioning",
          "label": "Positioning",
          "max": 2,
          "desc": "Confirmation / veto, not a driver. Crowd offside our trade is fuel; crowd already with us is unwind risk — a hard read (SI >10% float / extreme CoT, fund flows) plus a sentiment read (RSI at a crowded extreme). Clearly offside → 2 · neutral / mixed → 1 · clearly with us (unwind risk) → 0."
        },
        {
          "key": "technical",
          "label": "Technical",
          "max": 2,
          "desc": "Confirmation / veto, not a driver. Trend and entry agree with the thesis — 50/100/200-day moving-average alignment, Bollinger entry quality, Fibonacci off the trailing 6-month swing → 2 · mixed → 1 · contradicts → 0."
        }
      ],
      "tiers": [
        {
          "key": "High",
          "min": 75,
          "label": "High conviction"
        },
        {
          "key": "Medium",
          "min": 55,
          "label": "Medium conviction"
        },
        {
          "key": "Watch",
          "min": 0,
          "label": "Watchlist"
        }
      ],
      "bandsNote": "Score = raw ÷ 15 × 100. High ≥75 · Medium ≥55 · Watch ≥0. Data-quality cap: if any pillar's core input is estimated or unverified, the label cannot exceed Medium."
    }
  }
};
